### ISSUE TITLE
Some mods getting extra files from somewhere

### ISSUE THREAD

**Issue by delVhariant** [Mord3rca/gamma-launcher#100]
It seems like some mods end up getting files included that aren't in their zips and that don't get added via the official launcher.

One example is "Burn's Optimised World Models" from GAMMA Large Files.
The zipfile itself shows the following folders:
![image](https://github.com/Mord3rca/gamma-launcher/assets/57427820/414ccd73-a130-4538-8f83-64638c8c9879)

But after installing the mods folder shows additional folders (and extra files within):
![image](https://github.com/Mord3rca/gamma-launcher/assets/57427820/d9a28ec6-ef91-4ffa-8931-ec2eec2857fd)

I'm not sure where these extra files are coming from, but they seem to appear on all mods that are extracted from the GAMMA large files zip (I haven't looked at too many other mods just yet).

The files do also not appear within the git repo: https://github.com/Grokitach/gamma_large_files_v2/tree/main/Boomsticks%20and%20Sharpsticks%202022%20Guns/gamedata/configs/items/weapons

My guess is they are being incorrectly copied from a different location somehow?

**Comment by delVhariant** [comment]
Via the official launcher the files in the mods directory match what is in the downloaded zip.

I also noticed I put the wrong hyperlink in my initial posts to the github (same repo, wrong directory), the correct link is:
https://github.com/Grokitach/gamma_large_files_v2/tree/main/Burn's%20Optimised%20World%20Models/gamedata

The game does work with these differences, but there are some issues - the mp7 is the old model and has de-scynced sounds, and some weapons have broken names/descriptions are ones I noticed that made me look for the issue.

Doing a fresh install via gamma-launcher repeated the issue.
Removing everything in the mods directory and replacing it with the files from my windows install worked, as you would expect.

**Comment by delVhariant** [comment]
Is it possible that the TemporaryDirectory context is somehow getting re-used for zipfiles that contain multiple mods?
That would explain the propagation of files across multiple mods that are all stored in the same zipfile.

It does look like the rogue files I saw came from other mods within the gamma_large_files zip file.

**Comment by Mord3rca** [comment]
Can you test the quick fix ? Thanks !

**Comment by delVhariant** [comment]
> Can you test the quick fix ? Thanks !

The files certainly look correct from this branch!
