### ISSUE TITLE
gamma-launcher does nor produce identical files as original launcher

### ISSUE THREAD

**Issue by axet** [Mord3rca/gamma-launcher#106]
When gamma fully installed with gamma-laucnher it does create identical files as original gamma launcher. Recent update (2023-03-30) causing game to start with full red screen (shaders issues?). Anomaly Launcher does not start the game and exits immediately.

* https://ibb.co/ZJ2ChQH

After asking support on GAMMA discord server, turns out here is a recent virtual machine images with correct GAMMA installation. You can download them and compare it with folders created using gamma-launcher from:

https://all-seer.com/home/cdn/pub/games/gamma/

Running Meld on booth folders can show difference. I'm using gamma-lacuncher update from 2024-03-30 and robutt2 from 2024-03-28. And found:

Comparing Anomaly folder, showing gamma-launcher adding additional files, not present in GAMMA launcher installation:

* Anomaly/bin/G.A.M.M.A
* Missing Anomaly/AnomalyLauncher.cfg

Comparing GAMMA folder, showing gamma-launcher:

* Additional files: GAMMA/.Grok's Modpack Installer
* Missing mods files:
  * 101-BAS/*.dds (a lot)
  * 105 Re-sound/*.ogg (a lot)
  * a lot others...
* Additional mods:
  * 190 - Screen Space shaders 18.0

Different set of modlist.txt inside MO2 profiles (GAMMA/profiles/G.A.M.M.A)

**Comment by axet** [comment]
I'm reporting a bug. Since GAMMA installed using gamma-launcher not working - 1) showing a red screen. 2) AnomalyLaucnher wont start the game.

**Comment by Mord3rca** [comment]
Thanks, it's clearer.

1) Can you identify which mods cause the red screen ? I cannot reproduce it.

2) What are the logs of AnomalyLauncher ?

**Comment by axet** [comment]
1. No. Clean install. And Run. Game is in a red screen. By comparing gamma-launcher and GAMMA VM - here is a lot of differences in mods. A lot of missing files. Could be any of it
2. Anomaly Launcher logs? Where can I find those.

**Comment by axet** [comment]
2. You could be right. But how same wine prefix works fine with GAMMA VM?

```
0278:err:module:import_dll Library discord_game_sdk.dll (which is needed by L"Z:\\GAMMA\\mods\\185- Shader Driven Scopes - CrookR\\bin\\AnomalyDX11AVX.exe") not found
0278:err:module:import_dll Library icuuc65.dll (which is needed by L"Z:\\GAMMA\\mods\\185- Shader Driven Scopes - CrookR\\bin\\AnomalyDX11AVX.exe") not found
0278:err:module:import_dll Library tbb.dll (which is needed by L"Z:\\GAMMA\\mods\\185- Shader Driven Scopes - CrookR\\bin\\AnomalyDX11AVX.exe") not found
0278:err:module:loader_init Importing dlls for L"Z:\\GAMMA\\mods\\185- Shader Driven Scopes - CrookR\\bin\\AnomalyDX11AVX.exe" failed, status c0000135
```

After disabling MOD "185" Anomaly Launcher starts.

**Comment by Mord3rca** [comment]
@axet A fix was made for your issue on mod 185, can you test it ? Thanks
