### ISSUE TITLE
Failed to execute script 'gamma-launcher' due to unhandled exception!

### ISSUE THREAD

**Issue by LordHodenkobold** [Mord3rca/gamma-launcher#119]
Happend during:
`"./gamma-launcher check-anomaly --anomaly "/media/coato/1TB SSHD/anomaly"`
Will also happen during:
```
gamma-launcher check-md5 --gamma <GAMMA path>
gamma-launcher full-install --anomaly <Anomaly path> --gamma <GAMMA path>
```
```
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/check.py", line 45, in run
RuntimeError: Invalid file(s) detected:
/media/coato/1TB SSHD/anomaly/db/configs/configs.db0
/media/coato/1TB SSHD/anomaly/db/configs/scripts.db0
[56558] Failed to execute script 'gamma-launcher' due to unhandled exception!
```

**Comment by LordHodenkobold** [comment]
Linux Mint 21.3
Tried both Self-Contained Executable and tried "venv", same result 

`./gamma-launcher check-anomaly --anomaly "/media/coato/1TB SSHD/anomaly"`:
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/check.py", line 45, in run
RuntimeError: Invalid file(s) detected:
/media/coato/1TB SSHD/anomaly/db/configs/configs.db0
/media/coato/1TB SSHD/anomaly/db/configs/scripts.db0
[72021] Failed to execute script 'gamma-launcher' due to unhandled exception!

`./gamma-launcher check-md5 --gamma "/media/coato/1TB SSHD/gamma"`:
says for all mods:
not found on disk

`./gamma-launcher full-install --anomaly "/media/coato/1TB SSHD/anomaly" --gamma "/media/coato/1TB SSHD/gamma"`:
started to download, will update later if it worked.

Thanks for the fast reply, I hope what I send you was in anyway helpful, also thanks for your gamma-launcher. If you need anything else, just comment or write, for me it would be very helpful if you could send detailed steps for what you need, im pretty new to linux.

**Comment by Mord3rca** [comment]
If it is still an issue, please use `full-install` an two empty dirs (anomaly2, gamma2 for example) and send the full log (from the moment you run the command to its end) here

**Comment by Mord3rca** [comment]
No user feedback, will reopen if necessary
