### ISSUE TITLE
shaders broke after updating gamma

### ISSUE THREAD

**Issue by OolooOtsoop** [Mord3rca/gamma-launcher#120]
so my shaders were working perfectly until i updated the modpack a few weeks back. now i get the shader compilation failed error. is this possible to fix? if not it's not the end of the world i can just play with shaders disabled.

**Comment by Mord3rca** [comment]
Shader can be disabled see [README](https://github.com/Mord3rca/gamma-launcher?tab=readme-ov-file#shader-compilation-error).

If this is caused by a mod which is incorrectly install, feel free to put everything related to this issue here (what is installed with this launcher, what is installed by the official one, ....)

If not, this is a wine / upstream issue and this issue should be closed

**Comment by OolooOtsoop** [comment]
after a bunch of testing i found that mod "290- Atmospherics Shaders Weathers and Reshade - Hippobot" was causing the game to give me the shader compilation issue. 

to fix i purged my shader cache, disabled that mod and the game runs now.

**Comment by sadboi-drip** [comment]
[xray_steamuser.log](https://github.com/Mord3rca/gamma-launcher/files/15354052/xray_steamuser.log)
Not sure if this is a wine/upstream issue, but I removed reshade and the shader mods in the readme and still hitting shader compilation failures. I'm currently using ge-proton-9.4 and will attempt other versions in the meantime.

**Comment by sadboi-drip** [comment]
I've been having issues running meld. There is a bug with kwin_wayland on Fedora 40 and I'm currently unable to go that route for comparison. I will try running the downloaded gamma to see if it makes a difference, but this could just be an issue with the current Fedora as well. I'm hoping other Fedora users will drop in with some input.

**Comment by sadboi-drip** [comment]
I've gotten kwin and meld working, the only differences between the mods is that the ini files are on a one day lag behind the normal gamma rc3 folder

**Comment by sadboi-drip** [comment]
so a fedora update fixed the shader issue I think. I no longer get that error but instead a module not found error. The all-seer gamma instance is working though. 
[xray_steamuser.log](https://github.com/Mord3rca/gamma-launcher/files/15394173/xray_steamuser.log)

**Comment by Mord3rca** [comment]
```
[error][     126] : Module not found.
```

Looks like a Wine issue. On my side this is what my wineprefix have installed (with winetricks)
* d3dcompiler_43
* d3dcompiler_47
* d3dx10
* d3dx11_43
* d3dx9
* dxvk
* vcrun2019
* vcrun2022

**Comment by OolooOtsoop** [comment]
update: i have managed to fix my shader comp error by purging shader cache and reinstalling mod "290- Atmospherics Shaders Weathers and Reshade Latest - Hippobot". 
>right click the mod, then selected "reinstall mod". check boxes 00, 01, and 02. game ran fine with shaders fixed.
