### ISSUE TITLE
Unhandled Exception/Shell Breaking

### ISSUE THREAD

**Issue by MonitorZero** [Mord3rca/gamma-launcher#121]
Linux Mint 21.3
Kernel: 5.15.0-112-generic
Self-contained executable

I'm getting the following error when installing Anomaly. This will happen if I just install anomaly with anomaly-install or install everything with full-install but the full-install will break after the anomaly-install ends.

Error:
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/install.py", line 104, in run
  File "launcher/commands/check.py", line 39, in run
  File "launcher/commands/check.py", line 29, in _read_checksums
  File "pathlib.py", line 1058, in read_text
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/Steam/STALKER GAMMA/anomaly/tools/checksums.md5'
[12042] Failed to execute script 'gamma-launcher' due to unhandled exception!

This was when running "gamma-launcher anomaly-install --anomaly {path} --cache-directory {path}" However, it does work and functions as expected.

As you can see from the screenshot it also seems this function breaks my shell during extraction. Not sure if it's related or not.

![1](https://github.com/Mord3rca/gamma-launcher/assets/84548743/84391428-0dc8-4329-bb94-13d1c4c99e13)
![2](https://github.com/Mord3rca/gamma-launcher/assets/84548743/298be0de-6d7b-4ab3-a6ac-ec7a3e4df942)

**Comment by MonitorZero** [comment]
Forgot I have the checksums.md5 file but I'm not sure if it's exposed when it's being examined.
![3](https://github.com/Mord3rca/gamma-launcher/assets/84548743/c6bd84d3-a942-4c8c-bc4a-1d056efbdc52)

**Comment by Mord3rca** [comment]
I've made a fix, can you try it please ? (pip installation is required) Thanks !

**Comment by MonitorZero** [comment]
New error and still seems to break the shell. I did do a test with p7zip with just the anomaly zip file and it broke the shell exactly the same. It may be p7zip related?

Sorry, cleared the screen before I remembered to copy the error codes. My bad.

![10](https://github.com/Mord3rca/gamma-launcher/assets/84548743/76bcd615-3e3b-4631-9525-2edd7b08ec1d)
![11](https://github.com/Mord3rca/gamma-launcher/assets/84548743/adbfa7e7-c37a-447a-b4dc-453f635776a4)

**Comment by Mord3rca** [comment]
I'm sorry, my instructions were probably unclear:
* Can you download this [sources](https://github.com/Mord3rca/gamma-launcher/archive/refs/heads/fix/system_call.zip)
* Do an installation via venv / pip as explain [here](https://github.com/Mord3rca/gamma-launcher?tab=readme-ov-file#using-pip-from-source)

And try again, thanks :)

**Comment by MonitorZero** [comment]
Ah, yeah did not grab that one.

Ran it through a base anomaly-install and a full-install and they both worked flawlessly! Thank you! I was thinking of doing a video showing how to use your tool to install GAMMA so I hope we see a new release soon.

Thanks for your help!

**Comment by Mord3rca** [comment]
If you do a video, can you post the link here ? (just for curiosity)

**Comment by MonitorZero** [comment]
Of course!

**Comment by Mord3rca** [comment]
Master branch should always work with pip

Regarding the self exec, you can use this link to always point to the latest release:
https://github.com/Mord3rca/gamma-launcher/releases/latest/download/gamma-launcher
