### ISSUE TITLE
full-install stopping at T.H.A.P

### ISSUE THREAD

**Issue by MonitorZero** [Mord3rca/gamma-launcher#127]
Linux Mint 21.3
Kernel: 5.15.0-112-generic
Pip from source

Hello, since your update for [my last issue](https://github.com/Mord3rca/gamma-launcher/issues/121) the installer worked.

Due to trying to make a video I've had to delete that version and download the source directly and used the venv to install.

Everything works fine until the T.H.A.P. download/install. The script reports it has been downloaded and I can confirm that by checking gamma/downloads and I see the .zip file there.  This also seems to be the most recent version on Moddb [2.2.04](https://www.moddb.com/mods/stalker-anomaly/addons/thap-rework)

The script doesn't crash but it also doesn't continue at this point. I let it sit for about an hour but it just sat there. Also checked system monitor and no network activity or R/W was happening on the install drive.

This did not happen with the original fixed file you provided for my last issue.

I also noticed that in the GAMMA discord a mod updated and broke the installer so I assumed this had something to do with your script not working but they've since given the OK to start downloading again and I still have the issue.

Since the script doesn't crash I have no errors to provide but anything you would like me to test I'll be more than happy to.

**Comment by Mord3rca** [comment]
Hello,

Apparently `rarfile.RarFile` extract files one by one and since this archive have a lot of them ... It's pretty long.
Knowing that I'll probably do a fix to use `7z` instead ...

**Comment by Mord3rca** [comment]
@MonitorZero can you test PR #128 ? This should speed up extracting time

**Comment by MonitorZero** [comment]
Sure. I hate to ask but how can I test it? I see the changes but no place to download the modified version.

**Comment by MonitorZero** [comment]
Wait. I think I got the branch downloaded. I'll run through the install and let you know!

**Comment by MonitorZero** [comment]
@Mord3rca Tested and it literally blew past T.H.A.P in less than 2 seconds. I would call this resolved.

Thanks for the quick fix!

**Comment by Mord3rca** [comment]
No warning about a missing folder or something ? Everything is correctly installed ?

**Comment by MonitorZero** [comment]
Nope, I was able to use full-install and launch it using Steam with all Mods accounted for.

**Comment by MonitorZero** [comment]
So I was able to launch into MO2 but when launching from MO2 into Anomaly or GAMMA I get an "Unhandled exception occurred" 

I don't think this has anything to do with your script but I followed the instructions I had down exactly as I did when I could get it to work and I'm now getting this.

**Comment by MonitorZero** [comment]
I am seeing a lot of mods that are not set up when taking a closer look at MO2. I don't believe these were like this before. I can hit re-install on them to fix the flag in MO2 but it seems they may not have been install/extracted correctly?
![Screenshot from 2024-06-28 21-00-27](https://github.com/Mord3rca/gamma-launcher/assets/84548743/f68acbe4-e616-4cc2-820a-9b5fe7ba5ade)

**Comment by Mord3rca** [comment]
Installation logs are required to understand why the installation is incorrect.

It may be a definition issue. Can you do a `full-install` again and put the stdout output here ?

**Comment by MonitorZero** [comment]
[gammainstall.log](https://github.com/user-attachments/files/16041085/gammainstall.log)

Here's the output of the full-install command. I'm seeing a few warnings in it and went back to check a few and here's some that I looked into..

[+] Installing mod: THAP Rework
    Installing T.H.A.P. Rework 2.2 -> /home/andrew/Stalker/gamma/mods/23- THAP Rework - IENCE
    WARNING: T.H.A.P. Rework 2.2 does not exist
Says that this does not exist but it did install correctly in MO2

[+] Installing mod: Better sound
    Installing bin -> /home/andrew/Stalker/gamma/mods/10- Better sound - Grokitach
    WARNING: bin does not exist
Gave a warning but it is installed correctly in MO2

[+] Installing mod: Better Merc voicelines
8- Better Merc voicelines - TankeeGolf is not installed in MO2, Can't seem to find a file associated with this one in gamma/downloads. In gamma/mods there is an "8- Better Merc voicelines - TankeeGolf" mod but there are no files inside, just a meta.ini file

[+] Installing mod: Hit Effects
    Installing Wepl Hit Effects -> /home/andrew/Stalker/gamma/mods/16- Hit Effects - Wepl
    WARNING: Wepl Hit Effects does not exist
Not installed in MO2 - wepl_Hit_Effects.rar is present in gamma/downloads
16- Hit Effects - Wepl is present in gamma/mods but there are no files besides the meta.ini file

[+] Installing mod: High Res PDA Maps
    Installing High Res PDA Maps -> /home/andrew/Stalker/gamma/mods/26- High Res PDA Maps - Bazingarrey
    WARNING: High Res PDA Maps does not exist
Not installed in MO2 - High_Resolution_PDA_Maps.1.zip is present in gamma/downloads
26- High Res PDA Maps - Bazingarrey is present in gamma/mods but has no files besides the meta.ini

I can't seem to find a correlation between all of these. The ones I listed are various formats of .zip .7z and .rar I was thinking it might be format related.

The mod count is accurate and all the folders inside gamma/mods seems to be created but the extraction from the gamma/downloads to gamma/mods seems to be breaking for a few mods?

**Comment by Mord3rca** [comment]
Do you have unrar support in 7z ? (just try to decompress with the 7z utility, command can be found [here](https://github.com/Mord3rca/gamma-launcher/blob/master/launcher/archive.py#L63))

Mods are probably active / loaded because of a previous installation

**Comment by MonitorZero** [comment]
[7z.log](https://github.com/user-attachments/files/16041336/7z.log)
I ran "7z x -y wepl_Hit_Effects.rar -o/home/andrew/"

It came back with 255 errors
[7zErr.log](https://github.com/user-attachments/files/16041341/7zErr.log)

Just looking at the top 4 for /body/hit_exo_2.anm that was extracted. I can't tell if it's corrupt or not but I do see them listed in the extracted folder.

**Comment by Mord3rca** [comment]
Yup ... `7z` do not support rar file on your distro :/
Better fix the upstream module then.... Gonna be a bit longer

**Comment by MonitorZero** [comment]
Cool, so knowing that I went to my package manager and they do not include p7zip-rar module by default but it's available in the package manager.

I installed that and ran that previous command again with no errors at all. Idk if that helps you at all but unless you want me to test anything else with the current install I'll try running another full-install with p7zip-rar module installed and see if everything comes through correctly.

**Comment by Mord3rca** [comment]
Ok, now it should work ! If you have p7zip-rar module ...

**Comment by MonitorZero** [comment]
Tried again with your PR branch and it unfortunately did the same thing. The same items were not installed even though I now have the p7zip-rar module.

[gammainstall2.log](https://github.com/user-attachments/files/16042261/gammainstall2.log)

But my original issue has been fixed now this is a completely new issue. You can consider this closed if you want and I can put in a feature request for rar support on Mint 21.3 or you can continue with this issue. If you make any more headway on this I'm more than happy to keep testing but I assume this specific issue might be more of a long term fix instead of a quick fix?

**Comment by Mord3rca** [comment]
Are you sure to use the latest HEAD of `get_rid_of_rarfile_uncompress` branch ?

If you have are in a git directory use:
```sh
$ git fetch
$ git checkout origin/get_rid_of_rarfile_uncompress
(venv) $ pip install .
```

Decompression with `7z` should crash now if you dont have RAR support

**Comment by MonitorZero** [comment]
Ah, sorry. I've gotten the latest PR build now and tried it out.

Significantly less flags in MO2 and I can see in the installer where rar extraction is triggering. There are now only 5 mods that did not extract correctly.

26- High Res PDA Maps
34- Nicer Flashlights
141- Fixed Crashing when using multi use items
142- Fixed Crafting with multi use items
192- Cr3pis Icon Pack 

[full-install.log](https://github.com/user-attachments/files/16045455/full-install.log)

**Comment by Mord3rca** [comment]
Caused by a mod upgrade, all good then. This is an upstream definition issue. Thanks for all the testing :)

**Comment by MonitorZero** [comment]
Awesome, thank you for all your work! Hopefully Grok gets that updated at some point.
