### ISSUE TITLE
ModuleNotFoundError: No module named 'launcher.common'

### ISSUE THREAD

**Issue by sobkas** [Mord3rca/gamma-launcher#131]
With 3a4554e8e9b3b84823850f57d236bdb03279fc79
gamma-launcher fails with:
Traceback (most recent call last):
  File "/home/sobkas/gamma/bin/gamma-launcher", line 5, in <module>
    from launcher.cli import main
  File "/home/sobkas/gamma/lib/python3.11/site-packages/launcher/cli.py", line 2, in <module>
    from launcher.commands import (
  File "/home/sobkas/gamma/lib/python3.11/site-packages/launcher/commands/__init__.py", line 1, in <module>
    from .check import CheckAnomaly, CheckMD5
  File "/home/sobkas/gamma/lib/python3.11/site-packages/launcher/commands/check.py", line 7, in <module>
    from launcher.common import anomaly_arg, gamma_arg
ModuleNotFoundError: No module named 'launcher.common'

**Comment by Mord3rca** [comment]
My bad, I forget to add a file. Can you try again ?

**Comment by sobkas** [comment]
It fixes problem.
But on python 3.12 I'm getting:
gamma-launcher 
Traceback (most recent call last):
  File "/home/sobkas/gamma_test/bin/gamma-launcher", line 5, in <module>
    from launcher.cli import main
  File "/home/sobkas/gamma_test/lib/python3.12/site-packages/launcher/cli.py", line 2, in <module>
    from launcher.commands import (
  File "/home/sobkas/gamma_test/lib/python3.12/site-packages/launcher/commands/__init__.py", line 1, in <module>
    from .check import CheckAnomaly, CheckMD5
  File "/home/sobkas/gamma_test/lib/python3.12/site-packages/launcher/commands/check.py", line 9, in <module>
    from launcher.mods import read_mod_maker
  File "/home/sobkas/gamma_test/lib/python3.12/site-packages/launcher/mods/__init__.py", line 5, in <module>
    from launcher.mods.base import Base, Default
  File "/home/sobkas/gamma_test/lib/python3.12/site-packages/launcher/mods/base.py", line 4, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'

**Comment by sobkas** [comment]
pip install ~/repository/gamma-launcher/
Processing ./repository/gamma-launcher
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bs4 (from gamma-launcher==1.7)
  Using cached bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting platformdirs (from gamma-launcher==1.7)
  Using cached platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Collecting py7zr (from gamma-launcher==1.7)
  Using cached py7zr-0.21.1-py3-none-any.whl.metadata (17 kB)
Collecting rarfile (from gamma-launcher==1.7)
  Using cached rarfile-4.2-py3-none-any.whl.metadata (4.4 kB)
Collecting requests (from gamma-launcher==1.7)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tenacity (from gamma-launcher==1.7)
  Using cached tenacity-8.4.2-py3-none-any.whl.metadata (1.2 kB)
Collecting tqdm (from gamma-launcher==1.7)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting beautifulsoup4 (from bs4->gamma-launcher==1.7)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting texttable (from py7zr->gamma-launcher==1.7)
  Using cached texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting pycryptodomex>=3.16.0 (from py7zr->gamma-launcher==1.7)
  Using cached pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pyzstd>=0.15.9 (from py7zr->gamma-launcher==1.7)
  Using cached pyzstd-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)
Collecting pyppmd<1.2.0,>=1.1.0 (from py7zr->gamma-launcher==1.7)
  Using cached pyppmd-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.7 kB)
Collecting pybcj<1.1.0,>=1.0.0 (from py7zr->gamma-launcher==1.7)
  Using cached pybcj-1.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting multivolumefile>=0.2.3 (from py7zr->gamma-launcher==1.7)
  Using cached multivolumefile-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting inflate64<1.1.0,>=1.0.0 (from py7zr->gamma-launcher==1.7)
  Using cached inflate64-1.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting brotli>=1.1.0 (from py7zr->gamma-launcher==1.7)
  Using cached Brotli-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting psutil (from py7zr->gamma-launcher==1.7)
  Using cached psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Collecting charset-normalizer<4,>=2 (from requests->gamma-launcher==1.7)
  Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->gamma-launcher==1.7)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->gamma-launcher==1.7)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->gamma-launcher==1.7)
  Using cached certifi-2024.6.2-py3-none-any.whl.metadata (2.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4->gamma-launcher==1.7)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Using cached bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Using cached platformdirs-4.2.2-py3-none-any.whl (18 kB)
Using cached py7zr-0.21.1-py3-none-any.whl (67 kB)
Using cached rarfile-4.2-py3-none-any.whl (29 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached tenacity-8.4.2-py3-none-any.whl (28 kB)
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Using cached Brotli-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
Using cached certifi-2024.6.2-py3-none-any.whl (164 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached inflate64-1.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (96 kB)
Using cached multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Using cached pybcj-1.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (51 kB)
Using cached pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached pyppmd-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached pyzstd-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (414 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (290 kB)
Using cached texttable-1.7.0-py2.py3-none-any.whl (10 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Building wheels for collected packages: gamma-launcher
  Building wheel for gamma-launcher (pyproject.toml) ... done
  Created wheel for gamma-launcher: filename=gamma_launcher-1.7-py3-none-any.whl size=34601 sha256=0af224624fe8cdd81d51828f09a94bd20d73445811c029b30503741ceb1be389
  Stored in directory: /home/sobkas/.cache/pip/wheels/16/12/c9/173ab80d3f6c0fc9f436ced8e53d2d034173513c5a1bafc2ab
Successfully built gamma-launcher
Installing collected packages: texttable, brotli, urllib3, tqdm, tenacity, soupsieve, rarfile, pyzstd, pyppmd, pycryptodomex, pybcj, psutil, platformdirs, multivolumefile, inflate64, idna, charset-normalizer, certifi, requests, py7zr, beautifulsoup4, bs4, gamma-launcher
Successfully installed beautifulsoup4-4.12.3 brotli-1.1.0 bs4-0.0.2 certifi-2024.6.2 charset-normalizer-3.3.2 gamma-launcher-1.7 idna-3.7 inflate64-1.0.0 multivolumefile-0.2.3 platformdirs-4.2.2 psutil-6.0.0 py7zr-0.21.1 pybcj-1.0.2 pycryptodomex-3.20.0 pyppmd-1.1.0 pyzstd-0.16.0 rarfile-4.2 requests-2.32.3 soupsieve-2.5 tenacity-8.4.2 texttable-1.7.0 tqdm-4.66.4 urllib3-2.2.2

**Comment by Mord3rca** [comment]
Python 3.12 is not officially supported yet.

But to fix this issue: `pip install setuptools`

**Comment by sobkas** [comment]
7z-rar is unable to extract:
It extracts some of the files but fails with this two:
7z x  Gamma_inst/downloads/Dark_signal_Weapon_scape_audio_v2.8.rar

7-Zip 24.07 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-06-19
 64-bit locale=pl_PL.utf8 Threads:32 OPEN_MAX:1024

Scanning the drive for archives:
1 file, 76881074 bytes (74 MiB)

Extracting archive: Gamma_inst/downloads/Dark_signal_Weapon_scape_audio_v2.8.rar
--           
Path = Gamma_inst/downloads/Dark_signal_Weapon_scape_audio_v2.8.rar
Type = Rar
Physical Size = 76881074
Solid = -
Blocks = 2757
Multivolume = -
Volumes = 1

    
Would you like to replace the existing file:
  Path:     ./Dark signal stand alone weapon audio/Weapon rattle - lower - raising (bonus)/gamedata/scripts/eft_rattle.script
  Size:     1904 bytes (2 KiB)
  Modified: 2021-03-02 17:38:29
with the file from archive:
  Path:     Dark signal stand alone weapon audio/Weapon rattle - lower - raising (bonus)/gamedata/scripts/eft_rattle.script
  Size:     1904 bytes (2 KiB)
  Modified: 2021-03-02 17:38:29
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? A

ERROR: Unsupported Method : Dark signal stand alone weapon audio/Blindside weapon handling audio (bonus)/gamedata/sounds/weapons/aks74u/aks74u_reload.wav
ERROR: Unsupported Method : Dark signal stand alone weapon audio/Blindside weapon handling audio (bonus)/gamedata/sounds/weapons/aks74u/aks74u_reload_empty.wav
                                                                                                                                               
Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2

**Comment by Mord3rca** [comment]
Setting **GAMMA_LAUNCHER_USE_RARFILE** should work but one of the addon will take a long time to be installed.

Which distro are you using ?

**Comment by sobkas** [comment]
It taked like hours to install
Debian

apt policy 7zip 7zip-rar
7zip:
  Zainstalowana: 24.07+dfsg-1
  Kandydująca:   24.07+dfsg-1
  Tabela wersji:
 *** 24.07+dfsg-1 501
        501 http://ftp.pl.debian.org/debian unstable/main amd64 Packages
        500 http://ftp.pl.debian.org/debian testing/main amd64 Packages
        500 /var/lib/dpkg/status
7zip-rar:
  Zainstalowana: 24.07+ds-1
  Kandydująca:   24.07+ds-1
  Tabela wersji:
 *** 24.07+ds-1 501
        501 http://ftp.pl.debian.org/debian unstable/non-free amd64 Packages
        500 http://ftp.pl.debian.org/debian testing/non-free amd64 Packages
        500 /var/lib/dpkg/status

**Comment by Mord3rca** [comment]
Can you run `7z i` to confirm rar support ? Thanks

**Comment by sobkas** [comment]
7z i

7-Zip 24.07 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-06-19
 64-bit locale=pl_PL.utf8 Threads:32 OPEN_MAX:1024


Libs:
 0 : 24.07 : /usr/lib/7zip/7z.so
 1 : 24.07 : /usr/lib/7zip/Codecs/Rar.so

Formats:
 0 C...F..........c.a.m+.. w...0  7z       7z            7 z BC AF ' 1C
 0  ......................  APFS     apfs img      offset=32 N X S B 00
 0  ......................  APM      apm           E R
 0  ......................  Ar       ar a deb udeb lib ! < a r c h > 0A
 0  ......................  Arj      arj           ` EA
 0  K.....O.....X.........  Base64   b64           
 0  ......O...............  COFF     obj           
 0  ...F..................  Cab      cab           M S C F 00 00 00 00
 0  ......................  Chm      chm chi chq chw I T S F 03 00 00 00 ` 00 00 00
 0  ......................  Compound msi msp doc xls ppt D0 CF 11 E0 A1 B1 1A E1
 0  ....M.................  Cpio     cpio          0 7 0 7 0  ||  C7 q  ||  q C7
 0  ......................  CramFS   cramfs        offset=16 C o m p r e s s e d 20 R O M F S
 0  .....G..B.............  Dmg      dmg           k o l y 00 00 00 04 00 00 02 00
 0  .........E............  ELF      elf            E L F
 0  ......................  Ext      ext ext2 ext3 ext4 img offset=1080 S EF
 0  ......................  FAT      fat img       offset=510 U AA
 0  ......................  FLV      flv           F L V 01
 0  ......................  GPT      gpt mbr       offset=512 E F I 20 P A R T 00 00 01 00
 0  ....M.................  HFS      hfs hfsx      offset=1024 B D  ||  H + 00 04  ||  H X 00 05
 0  ...F..................  Hxs      hxs hxi hxr hxq hxw lit I T O L I T L S 01 00 00 00 ( 00 00 00
 0  ......O...............  IHex     ihex          
 0  ......................  Iso      iso img       offset=32769 C D 0 0 1
 0  ......................  LP       lpimg img     offset=4096 g D l a 4 00 00 00
 0  ......................  Lzh      lzh lha       offset=2 - l h
 0  .......P..............  MBR      mbr           
 0  ....M....E............  MachO    macho         CE FA ED FE  ||  CF FA ED FE  ||  FE ED FA CE  ||  FE ED FA CF
 0  ......................  MsLZ     mslz          S Z D D 88 F0 ' 3 A
 0  ....M.................  Mub      mub           CA FE BA BE 00 00 00  ||  B9 FA F1 0E
 0  ......................  NTFS     ntfs img      offset=3 N T F S 20 20 20 20 00
 0  ...F.G................  Nsis     nsis          offset=4 EF BE AD DE N u l l s o f t I n s t
 0  .........E............  PE       exe dll sys   M Z
 0  ......................  Ppmd     pmd           8F AF AC 84
 0  ......................  QCOW     qcow qcow2 qcow2c Q F I FB 00 00 00
 0  ...F..................  Rar      rar r00       R a r ! 1A 07 00
 0  ...F..................  Rar5     rar r00       R a r ! 1A 07 01 00
 0  ......................  Rpm      rpm           ED AB EE DB
 0  K.....................  SWF      swf           F W S
 0  ....M.................  SWFc     swf (~.swf)   C W S  ||  Z W S
 0  ......................  Sparse   simg img      : FF & ED 01 00
 0  ......................  Split    001           
 0  ....M.................  SquashFS squashfs      h s q s  ||  s q s h  ||  s h s q  ||  q s h s
 0  .........E............  TE       te            V Z
 0  ...FM.................  UEFIc    scap          BD 86 f ; v 0D 0 @ B7 0E B5 Q 9E / C5 A0  ||  8B A6 < J # w FB H 80 = W 8C C1 FE C4 M  ||  B9 82 91 S B5 AB 91 C B6 9A E3 A9 C F7 / CC
 0  ...FM.................  UEFIf    uefif         offset=16 D9 T 93 z h 04 J D 81 CE 0B F6 17 D8 90 DF  ||  x E5 8C 8C = 8A 1C O 99 5 89 a 85 C3 - D3
 0  ....M.O...............  Udf      udf iso img   offset=32768 00 B E A 0 1 01 00  ||  01 C D 0 0 1
 0  ......................  VDI      vdi           offset=64  10 DA BE
 0  .....G................  VHD      vhd           c o n e c t i x 00 00
 0  ......................  VHDX     vhdx avhdx    v h d x f i l e
 0  ......................  VMDK     vmdk          K D M V
 0  ......................  Xar      xar pkg xip   x a r ! 00
 0  ......................  Z        z taz (.tar)  1F 9D
 0 CK.....................  bzip2    bz2 bzip2 tbz2 (.tar) tbz (.tar) B Z h
 0 CK.................m+.. .u..1  gzip     gz gzip tgz (.tar) tpz (.tar) apk (.tar) 1F 8B 08
 0  K.....O...............  lzma     lzma          
 0  K.....................  lzma86   lzma86        
 0 C......O...LH......m+.. wu.n1  tar      tar ova       offset=257 u s t a r
 0 C.SN.......LH..c.a.m+.. w...0  wim      wim swm esd ppkg M S W I M 00 00 00
 0 CK.....................  xz       xz txz (.tar) FD 7 z X Z 00
 0 C...FMG........c.a.m+.. wud.0  zip      zip z01 zipx jar xpi odt ods docx xlsx epub ipa apk appx P K 03 04  ||  P K 05 06  ||  P K 06 06  ||  P K 07 08 P K  ||  P K 0 0 P K
 0  K.....................  zstd     zst tzst (.tar) ( B5 / FD
   CK.....O.....XC........  Hash     sha256 sha512 sha224 sha384 sha1 sha md5 crc32 crc64 asc cksum 

Codecs:
 0 4ED   303011B BCJ2
 0  EDF  3030103 BCJ
 0  EDF  3030205 PPC
 0  EDF  3030401 IA64
 0  EDF  3030501 ARM
 0  EDF  3030701 ARMT
 0  EDF  3030805 SPARC
 0  EDF        A ARM64
 0  EDF        B RISCV
 0  EDF    20302 Swap2
 0  EDF    20304 Swap4
 0  ED     40202 BZip2
 0  ED         0 Copy
 0  ED     40109 Deflate64
 0  ED     40108 Deflate
 0  EDF        3 Delta
 0  ED        21 LZMA2
 0  ED     30101 LZMA
 0  ED     30401 PPMD
 0  EDF  6F10701 7zAES
 0  EDF  6F00181 AES256CBC
 1   D     40301 Rar1
 1   D     40302 Rar2
 1   D     40303 Rar3
 1   D     40305 Rar5

Hashers:
      4        1 CRC32
 0    4        1 CRC32
 0   20      201 SHA1
 0   32        A SHA256
 0    8      211 XXH64
 0    8        4 CRC64
 0   32      202 BLAKE2sp

**Comment by sobkas** [comment]
Also while doing usvfs-workaround:
Installing DarkasleQif's and iTheon's Parts Condition Color Thresholds Changes
    --> Failed: cannot copy tree 'Gamma_inst/mods/DarkasleQif's and iTheon's Parts Condition Color Thresholds Changes': not a directory
There is no Q in the name

**Comment by Mord3rca** [comment]
Weird .... 7z have rar support ....


Regarding the 2nd message, upstream definition error: https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_data/modlist.txt#L123

**Comment by Mord3rca** [comment]
Well .... 7z can't extract all rar archives even with unrar support ... Gonna do a fix in rarfile module then...
