### ISSUE TITLE
Attempting to use second-level arguments returns unrecognized argument error.

### ISSUE THREAD

**Issue by Communing-With-Coyotes** [Mord3rca/gamma-launcher#141]
The issue:
First-level arguments are accepted
`gamma-launcher --version` >> gamma-launcher 1.7
`gamma-launcher anomaly-install` >> error: the following arguments are required --anomaly
`gamma-launcher anomaly-install --anomaly <my_anomaly_path>` error: unrecognized arguments

This is just an example, but no second-level arguments work. They all returned an `unrecognized arguments` error. I haven't done any regression testing to see which commit this started happening, but it's certainly not working on [6b282f5](https://github.com/Mord3rca/gamma-launcher/commit/6b282f527553f3a35c50d37b65929a50093d7474)

**Comment by Mord3rca** [comment]
Hey !

I can't reproduce this issue with the self contain executable and on master.... Can you print the content of **~/.config/gamma-launcher/config.ini** you may have an invalid entry here.

**Comment by Mord3rca** [comment]
Is this still an issue ?
