### ISSUE TITLE
RuntimeERROR :7z error will decomprassing ...

### ISSUE THREAD

**Issue by Cheezik** [Mord3rca/gamma-launcher#145]
I have 0 clues on whats broken nor what happend, I know i have 7z and python installed and working correctly
![image](https://github.com/user-attachments/assets/0c182a57-7163-4803-9770-266352513697)
If anyone has any ideas please lmk <3

**Comment by Mord3rca** [comment]
Hey !

You are using the self contain executable on a distro which is probably not Ubuntu.
Please use the `pip` installation or AUR install (see this [PR](https://github.com/Mord3rca/gamma-launcher/pull/140/files)) and try again

**Comment by Cheezik** [comment]
Thank you so much, im just plain stupid and should have seen it has been build with ubuntu..
(maybe also merge the pr so its visible)

**Comment by Mord3rca** [comment]
I was waiting for a confirmation since I'm not using arch, thanks a lot ! Since it works for you, I'll merge.

**Comment by Cheezik** [comment]
Just quickly poping in, It works like a charm. Thanks for your work <3
