### ISSUE TITLE
fatal: Could not reset index file to revision 'HEAD'.'

### ISSUE THREAD

**Issue by googl267** [Mord3rca/gamma-launcher#154]
System: 
CPU - Intel® Core™ i5-8500 CPU @ 3.00GHz
Mem - 15.5 GiB of RAM
GPU - AMD Radeon RX 6800
Kernal - 6.10.12-200.fc40.x86_64 (64-bit)
OS - Fedora 40

I tried at first with the release binary which kept erroring when pulling from git, however I believe that was a system package problem since I'm on Fedora. I then built from git in venv and ran `full-install` which worked perfectly until:
```
(basically every asset in the game)...
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_neutral-lut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_permtexture.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/ssdonoise.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/waow.png
error: unable to write file modpack_patches/bin/soft_oal.dll
error: unable to write file modpack_patches/bin/soft_oal.dll.back
Updating files: 100% (6757/6757), done.
fatal: Could not reset index file to revision 'HEAD'.'
```
I tried both with cached files and letting gamma-launcher pull things and both came to the same error

`check-anomaly` runs normally 
`check-md5` fails

**Comment by Mord3rca** [comment]
Hey !
Can you check if you have enough free space on /tmp ? ( `df -h /tmp` )

**Comment by googl267** [comment]
I have 8gb on tmp with only 1% used

**Comment by Mord3rca** [comment]
gamma_setup.git required 8.9 Gb :/

```sh
$ mkdir /tmp/test-checkout; git worktree add /tmp/test-checkout Grokitach/main; du -hd0 /tmp/test-checkout
Preparing worktree (detached HEAD cb58077)
Updating files: 100% (6757/6757), done.
HEAD is now at cb58077 2.7Gb client Part3
8.9G	/tmp/test-checkout
```

**Comment by googl267** [comment]
Gamma setup perfectly after changing temp thanks!
