### ISSUE TITLE
Errors when installing

### ISSUE THREAD

**Issue by ToRRent1812** [Mord3rca/gamma-launcher#157]
Hi, i'm trying to install gamma but I see 2 different errors
If I install through pip/venv, the moment I type
`gamma-launcher full-install --anomaly Anomaly --gamma Gamma`
I see this

> Traceback (most recent call last):
>   File "/home/rabbit/Pobrane/env/bin/gamma-launcher", line 5, in <module>
>     from launcher.cli import main
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/launcher/cli.py", line 2, in <module>
>     from launcher.commands import (
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/launcher/commands/__init__.py", line 1, in <module>
>     from .check import CheckAnomaly, CheckMD5
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/launcher/commands/check.py", line 10, in <module>
>     from launcher.mods import read_mod_maker
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/launcher/mods/__init__.py", line 5, in <module>
>     from launcher.mods.archive import extract_archive
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/launcher/mods/archive.py", line 5, in <module>
>     from unrar.rarfile import RarFile
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/unrar/rarfile.py", line 26, in <module>
>     from unrar import unrarlib
>   File "/home/rabbit/Pobrane/env/lib64/python3.11/site-packages/unrar/unrarlib.py", line 54, in <module>
>     unrarlib = ctypes.cdll.LoadLibrary(lib_path)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
>     return self._dlltype(name)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/ctypes/__init__.py", line 376, in __init__
>     self._handle = _dlopen(self._name, mode)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: /lib64/glibc-hwcaps/x86-64-v3/libunrar.so.7.0.9: undefined symbol: _Z14RecVolumesTestP11CommandDataP7ArchiveRKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE

And the moment I download release binary(not pip/venv from source), i see this

> Traceback (most recent call last):
>   File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
>   File "ctypes/__init__.py", line 376, in __init__
> OSError: /lib64/glibc-hwcaps/x86-64-v3/libunrar.so.7.0.9: undefined symbol: _Z14RecVolumesTestP11CommandDataP7ArchiveRKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "gamma-launcher.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/cli.py", line 2, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/commands/__init__.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/commands/check.py", line 10, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/mods/__init__.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/mods/archive.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "unrar/rarfile.py", line 26, in <module>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "unrar/unrarlib.py", line 54, in <module>
>   File "ctypes/__init__.py", line 454, in LoadLibrary
>   File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
> pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'libunrar.so.7.0.9'. Most likely this dynlib/dll was not found when the application was frozen.
> [PYI-38435:ERROR] Failed to execute script 'gamma-launcher' due to unhandled exception!

What can I do with it?

**Comment by Mord3rca** [comment]
Hello, can you precise which distro are you using ?

Can you try to decompress something with `unrar` and see if the symbol issue appear ?

Thanks

**Comment by ToRRent1812** [comment]
I succesfully extracted .rar with unrar

**Comment by Mord3rca** [comment]
Can you retry by uninstalling **libunrar7_0_9-x86-64-v3** and installing **libunrar7_0_9** ?

**Comment by ToRRent1812** [comment]
Unfortunately the issue still persists :/

**Comment by Mord3rca** [comment]
Well .... library from your repo are invalid (a symbol is missing) so you'll have to compile it yourself:
* Delete libunrar from your system: `zypper rm libunrar7_0_9`
* Install g++ and make with: `zypper in gcc14-c++ make`
* In a workdir, clone unrar with: `git clone https://github.com/pmachapman/unrar.git`
* Then: `cd unrar; make CXX=g++-14 lib`

Now, when you want to use gamma-launcher from venv, use: `LD_LIBRARY_PATH=/path/to/compiled/libunrar gamma-launcher ....`

**Comment by Mord3rca** [comment]
It may be interesting to do a bug report to OpenSuse for this, here are the details:

Missing symbols:
> RecVolumesTest(CommandData*, Archive*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)
> RecVolumesRestore(CommandData*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, bool)

Both are defined in this file: https://github.com/pmachapman/unrar/blob/master/recvol.cpp

**Comment by kalrach** [comment]
> Well .... library from your distro is invalid (a symbol is missing) so you'll have to compile it yourself:
> 
> * Delete libunrar from your system: `zypper rm libunrar7_0_9`
> * Install g++ and make with: `zypper in gcc14-c++ make`
> * In a workdir, clone unrar with: `git clone https://github.com/pmachapman/unrar.git`
> * Then: `cd unrar; make CXX=g++-14 lib`
> 
> Now, when you want to use gamma-launcher from venv, use: `LD_LIBRARY_PATH=/path/to/compiled/libunrar gamma-launcher ....`

Hello, I have ran into the same issue and attempted the LD_LIBRARY_PATH work around and still getting the same error, I even added the compiled unrar library directory to my $PATH variable.

Here is the log from inside the venv:

> Traceback (most recent call last):
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/bin/gamma-launcher", line 5, in <module>
>     from launcher.cli import main
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/cli.py", line 2, in <module>
>     from launcher.commands import (
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/__init__.py", line 1, in \<module\>
>     from .check import CheckAnomaly, CheckMD5
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/check.py", line 10, in \<module\>
>     from launcher.mods import read_mod_maker
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/mods/__init__.py", line 5, in \<module\>
>     from launcher.mods.archive import extract_archive
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/mods/archive.py", line 5, in \<module\>
>     from unrar.rarfile import RarFile
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/unrar/rarfile.py", line 26, in <module>
>     from unrar import unrarlib
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/unrar/unrarlib.py", line 57, in <module>
>     raise LookupError("Couldn't find path to unrar library.")
> LookupError: Couldn't find path to unrar library.

The log when running the standalone script is not much different:

> Traceback (most recent call last):
>   File "gamma-launcher.py", line 5, in \<module\>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/cli.py", line 2, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/commands/__init__.py", line 1, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/commands/check.py", line 10, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/mods/__init__.py", line 5, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/mods/archive.py", line 5, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "unrar/rarfile.py", line 26, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "unrar/unrarlib.py", line 57, in \<module\>
> LookupError: Couldn't find path to unrar library.
> [PYI-6959:ERROR] Failed to execute script 'gamma-launcher' due to unhandled exception!

**Comment by Mord3rca** [comment]
Please provide the command line used

**Comment by kalrach** [comment]
For the LD_LIBRARY_PATH workaround inside the venv:
`LD_LIBRARY_PATH=/home/kalrach/repos/unrar/ gammma-launcher fullinstall --anomaly /media/gamesv/lutris/stalker-gamma/drive_c/Anomaly --gamma /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA --cache-directory /media/gamesv/lutris/stalker-gamma/drive_c/gamma_cache`

When that didn't work I set the $PATH with `export PATH=/home/kalrach/repos/unrar/:$PATH` and then ran `gamma-launcher fullinstall --anomaly /media/gamesv/lutris/stalker-gamma/drive_c/Anomaly --gamma /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA --cache-directory /media/gamesv/lutris/stalker-gamma/drive_c/gamma_cache`

When that did work, I deactivated the venv and attempted to run the standalone script with the same command as above except instead of `gamma-launcher` I ran `./gamma-launcher` in my drive_c directory. Just to note I had the venv in it's own directory inside `drive_c` under `drive_c/gl` just to keep everything contained. I also made sure that the compiled unrar library was in the PATH before running the script inside the venv and outside the venv.

**Comment by Mord3rca** [comment]
Try again after running `zypper in unrar`

**Comment by kalrach** [comment]
> Try again after running `zypper in unrar`

Here are the steps I did after reinstalling libunrar using yast.

The command ran outside the venv for the standalone version of the script: `./gamma-launcher fullinstall --anomaly /media/gamesv/lutris/stalker-gamma/drive_c/Anomaly --gamma /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA --cache-directory /media/gamesv/lutris/stalker-gamma/drive_c/gamma_cache`

This is the log from outside the venv using the standalone script with the tumbleweed version of libunrar installed, it's no different from the person before me:
> ./gamma-launcher fullinstall --anomaly /media/gamesv/lutris/stalker-gamma/drive_c/Anomaly --gamma 
> /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA --cache-directory /media/gamesv/lutris/stalker-gamma/drive_c/gamma_cache
> Traceback (most recent call last):
>   File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
>   File "ctypes/__init__.py", line 376, in __init__
> OSError: /lib64/glibc-hwcaps/x86-64-v3/libunrar.so.7.0.9: undefined symbol: _Z14RecVolumesTestP11CommandDataP7ArchiveRKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "gamma-launcher.py", line 5, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/cli.py", line 2, in \<module\>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/commands/__init__.py", line 1, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/commands/check.py", line 10, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/mods/__init__.py", line 5, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "launcher/mods/archive.py", line 5, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "unrar/rarfile.py", line 26, in <module>
>   File "\<frozen importlib._bootstrap\>", line 1176, in _find_and_load
>   File "\<frozen importlib._bootstrap\>", line 1147, in _find_and_load_unlocked
>   File "\<frozen importlib._bootstrap\>", line 690, in _load_unlocked
>   File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
>   File "unrar/unrarlib.py", line 54, in <module>
>   File "ctypes/__init__.py", line 454, in LoadLibrary
>   File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
> pyimod03_ctypes.install.\<locals\>.PyInstallerImportError: Failed to load dynlib/dll 'libunrar.so.7.0.9'. Most likely this dynlib/dll was not found when the application was frozen.
> [PYI-8590:ERROR] Failed to execute script 'gamma-launcher' due to unhandled exception!

I then `cd`'ed into the the clone of gamma-luancher repo to activate the venv, and activated it using `source env/bin/activate`

The command I ran inside the venv `gamma-launcher fullinstall --anomaly /media/gamesv/lutris/stalker-gamma/drive_c/Anomaly --gamma /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA --cache-directory /media/gamesv/lutris/stalker-gamma/drive_c/gamma_cache`

This is the log from inside the venv with the tumbleweed version of unrar installed:
> Traceback (most recent call last):
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/bin/gamma-launcher", line 5, in \<module\>
>     from launcher.cli import main
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/cli.py", line 2, in <module>
>     from launcher.commands import (
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/__init__.py", line 1, in <module>
>     from .check import CheckAnomaly, CheckMD5
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/check.py", line 10, in <module>
>     from launcher.mods import read_mod_maker
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/mods/__init__.py", line 5, in <module>
>     from launcher.mods.archive import extract_archive
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/mods/archive.py", line 5, in <module>
>     from unrar.rarfile import RarFile
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/unrar/rarfile.py", line 26, in <module>
>     from unrar import unrarlib
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/unrar/unrarlib.py", line 54, in <module>
>     unrarlib = ctypes.cdll.LoadLibrary(lib_path)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
>     return self._dlltype(name)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/ctypes/__init__.py", line 376, in __init__
>     self._handle = _dlopen(self._name, mode)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: /lib64/glibc-hwcaps/x86-64-v3/libunrar.so.7.0.9: undefined symbol: _Z14RecVolumesTestP11CommandDataP7ArchiveRKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE

By the time I had started troubleshooting with the `LD_LIBRARY_PATH` the script had already failed with the tumbleweed version of unrar and had completely uninstalled it using yast.

Please note on Opensuse Tumbleweed unrar, libunrar7_0_9, and libunrar7_0_9-x86-64-v3 are all separate packages, one only installs the commandline utility and the other two only install the dynamic libraries. The commandline utility doesn't require libunrar7_0_9 to be installed but libunrar7_0_9 requires libunrar7_0_9-x86-64-v3.

Is there any other information you need?

**Comment by Mord3rca** [comment]
You have 2 issues here, the OSError is fixed by the recompiling of the lib and setting LD_LIBRARY_PATH

The second one is LookupError which is caused by the missing exec `unrar` (not the lib)

**Comment by kalrach** [comment]
I never uninstalled the `unrar` executable package. I only uninstalled the libunrar packages to test the locally compiled lib and setting the LD_LIBRARY_PATH variable only when the system version of the lib is not installed.

**Comment by Mord3rca** [comment]
I'll test this again in Docker when I can

**Comment by Mord3rca** [comment]
Hello again, just retested and indeed, I kinda messed things up.

The command to type is: `UNRAR_LIB_PATH=/path/to/libunrar.so gamma-launcher full-install [...]` to use your newly compiled library.

Also, make sure `7zip` is installed with `zypper in 7zip`

**Comment by kalrach** [comment]
> The command to type is: `UNRAR_LIB_PATH=/path/to/libunrar.so gamma-launcher full-install [...]` to use your newly compiled library.
It worked! Everything installed, only snag was the script hanged for about 20 minutes until I killed it with `ctrl+c` and tried again with a vpn connection which fixed the issue.

> Also, make sure `7zip` is installed with `zypper in 7zip`
Usually have this installed anyways, but I doubled checked.

It hung at this point in the process:

> [+] Installing mod: Attachment Alignment Fixes
> Extracting /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA/downloads/master.zip
>     Installing Tiskar-s-Burn-s-Attachment-Alignment-Fixes-master -> /media/gamesv/lutris/stalker-gamma/drive_c/GAMMA/mods/368- Attachment Alignment Fixes - Tiskar & Burn

And gave this error when I killed it with `ctrl+c`:

> ^CTraceback (most recent call last):
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/bin/gamma-launcher", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/cli.py", line 113, in main
>     args.cobject().run(args)
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/install.py", line 306, in run
>     self._install_mods()
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/install.py", line 254, in _install_mods
>     mod.download(self._dl_dir, use_cached=True)
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/mods/downloader/moddb.py", line 91, in download
>     metadata = parse_moddb_data(self._iurl) if self._iurl else {}
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/mods/downloader/moddb.py", line 16, in parse_moddb_data
>     r = g_session.get(url)
>         ^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/requests/sessions.py", line 602, in get
>     return self.request("GET", url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/requests/adapters.py", line 667, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
>     response = conn.getresponse()
>                ^^^^^^^^^^^^^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/urllib3/connection.py", line 507, in getresponse
>     httplib_response = super().getresponse()
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/http/client.py", line 1395, in getresponse
>     response.begin()
>   File "/usr/lib64/python3.11/http/client.py", line 325, in begin
>     version, status, reason = self._read_status()
>                               ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/http/client.py", line 286, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/socket.py", line 718, in readinto
>     return self._sock.recv_into(b)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/ssl.py", line 1314, in recv_into
>     return self.read(nbytes, buffer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/ssl.py", line 1166, in read
>     return self._sslobj.read(len, buffer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyboardInterrupt

I was able to finish the installation after switching to a vpn and the game ran with no issues afterwards.

**Comment by Mord3rca** [comment]
Glad it works !

@ToRRent1812 Can you test the solution on your side too ? And close this issue if it works. Thanks

**Comment by ToRRent1812** [comment]
I can confirm, this fixes the issue, thank You.
