### ISSUE TITLE
GAMMA is installed with corrupted/missing mods

### ISSUE THREAD

**Issue by kalrach** [Mord3rca/gamma-launcher#158]
Multiple mods are missing after installing. I didn't notice it until I attempted to put an artifact in to an artifact container and caused a crash.  I checked MD5 sums using the `check-md5` command for the script and it returned with an error. I have deleted an reinstalled GAMMA with the same result, I even cleared cache directory to ensure a clean install and checked the MD5 sums again, resulting in the same error. 

When checking the MD5 sums I get this error, I have included the last two checks for context:

> Calculating hash of Soundscape_Overhaul_3.0.zip: 100%|#################################################################################################################################################################################################| 339M/339M [00:00<00:00, 872MiB/s]
> Calculating hash of Groks_main_menu_theme.zip: 100%|#################################################################################################################################################################################################| 7.05M/7.05M [00:00<00:00, 181MiB/s]
> Traceback (most recent call last):
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/bin/gamma-launcher", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/cli.py", line 113, in main
>     args.cobject().run(args)
>   File "/media/gamesv/lutris/stalker-gamma/drive_c/gl/env/lib64/python3.11/site-packages/launcher/commands/check.py", line 84, in run
>     print("\n".join(errors))
>           ^^^^^^^^^^^^^^^^^
> TypeError: sequence item 0: expected str instance, HashError found

The thing I noticed during install the second time around is that there were multiple instances of a "WARNING" message stating that \<mod name\> does not exist. This is the output after running `grep WARNING install.log`:

>WARNING: Xenotech, Seryoga, Gonta, Crab, Garmata, Pilot, Tourist combat behavior  does not exist
>WARNING: Black_Market-main does not exist
>WARNING: Steyr Scout Dual Pack - REDUX does not exist
>WARNING: ADD THIS IF NOT USING DX11 does not exist
>WARNING: CS Eden's GAMMA Loading Screens does not exist
>WARNING: 01 Reposition does not exist
>WARNING: More_Portrait_Icons does not exist
>WARNING: Mags Patch does not exist
>WARNING: 00. Grass does not exist
>WARNING: 01. Trees does not exist
>WARNING: 02. Dead pines does not exist
>WARNING: 03. Autumn bush does not exist
>WARNING: RE-SOUND BLINDSIDE ANIMS BY YUNGPR1NCE_DLTX does not exist
>WARNING: RE-SOUND BLINDSIDE ANIMS BY YUNGPR1NCE_DLTX_Patch_BaS does not exist
>WARNING: ABF ) ARX - Module 2 - Anomalies + Actor + Poltergeist does not exist
>WARNING: 3. Poltergeist harder does not exist
>WARNING: Soundscape Burer Compatibility does not exist
>WARNING: dyn tasks does not exist
>WARNING: Main + Weapon Parts Overhaul Patch does not exist
>WARNING: Main does not exist
>WARNING: scripts does not exist
>WARNING: Anomaly-Mod-Configuration-Menu does not exist
>WARNING: 3 - German #4 does not exist
>WARNING: BAS_sound_fix-main does not exist
>WARNING: Anomaly Tacticool Scopes does not exist
>WARNING: BaS adaptation does not exist
>WARNING: [PATCH] EFT Reposition does not exist
>WARNING: exo servo patch does not exist
>WARNING: anomaly-exo-latest does not exist
>WARNING: Stealth_2.0 does not exist
>WARNING: Nicer Flashlights Addon Imperfect 9 does not exist
>WARNING: High Res PDA Maps does not exist
>WARNING: bin does not exist

When checking mod organizer these mods are flagged as having "no game data."
![Screenshot_20241020_212548](https://github.com/user-attachments/assets/71de87b9-ed2d-4847-ae08-61103b579578)

All bad mods grouped together:
![Screenshot_20241020_225933](https://github.com/user-attachments/assets/2fc2dfa3-8d0e-4d87-8fea-a2c8470a4ab3)

The following is a github gist with the complete logs for both the install and the MD5 check including the complete commands ran: https://gist.github.com/kalrach/34962c25382162f80dfaf4be6c33ec57

**Comment by Mord3rca** [comment]
Hello, branch `fix/check_md5_cmd` should resolve your issue with check md5.

Regarding the 2nd issue, this is probably an upstream definition issue. Some mods are updated on ModDB and installation instruction become obsolete. GAMMA cannot be versioned because of that.

If you wish to do a bug report on this launcher, please DL the result of the official launcher [here](https://all-seer.com/cdn/games/gamma/), create a diff with `meld` or something similar and create a detail report on what was missing / installed incorrectly.

Just for reference, this launcher do not aim to create a bit / bit install of the official one ... but having a functional game on Linux.

**Comment by kalrach** [comment]
Understood, using the GAMM10-14.7z file from your link. There are a total of 46 mods with either missing assets or missing entirely; many of them are just mods which had their fomod assets installed on the sample archive. I will sort though the data on meld and provide a more detailed report once complete.

**Comment by JoelTurtiainen** [comment]
Im having the same issue with those mods, could the issue be that it downloads them with generic names? such as: latest, main, and master.zip

**Comment by Mord3rca** [comment]
@JoelTurtiainen can you retry with #160 to see if it's better ?

**Comment by kalrach** [comment]
The following is a complete report of my findings using meld after running the script using the #160 branch patch.

> 101 - BAS scopes extravaganza 2d shader-based-scopes patch - Kuez
>     # Mod root available but missing all data
> 
> 105 - Re-sound for BAS sniper and pistols - Rex1534
>     # Missing '1.5.1 BAS' folder in mod root/
>     # Missing '1.5.2 BAS' folder in mod root/
> 
> 11 - Preblowout Murder - Ethylia
>     # Missing 'optional' folder in mod root/
> 
> 122 - Zone Tales in Load Screens - Oni
>     # gamedata folder name is slightly different (gamedata instead of Gamedata),
>     # may not be an issue but better to note it than not
> 
> 141 - Fixed Crafting with Multi-Use Items - thisisntmysteamid
>     # Missing 'gamedata' folder in mod root/
> 
> 142 - 141 - Fixed Crafting with Multi-Use Items WPO patch - thisisntmysteamid
>     # Missing 'gamedata' folder in mod root/
> 
> 164 - Hunger Thirst Sleep UI - xcvb
>     # Mod folder completely missing
> 
> 193 - Maids HD Icons (right click and reinstall if you want to use it) - Maids
>     # 'Images' folder missing from mod root/
>     # 'dds' folder missing from mod root/
>     # 'dltx' folder missing from mod root/
>     # 'externalpatches' folder missing from mod root/
> 
> 213- Trader Overhaul (if you do not want the true GAMMA experience) - AGoodSetOfPistol
>     # Missing '1.5.2 Update Version' folder in mod root/
>     # Missing 'Optional files' folder in mod root/
> 
> 241- Simple Autumn Retexture No leaves - Daedalus-Prime
>     # 'db' folder installed directly to mod root instead of inside 'gamedata'
> 
> 242- Gardener of the Zone Textures - YuriVernadsky
>     # Missing 'gamedata' folder in mod root
> 
> 271- G.A.M.M.A. Large Files - GAMMA Team
>     # Mod folder completely missing
> 
> 272- Grulag's Dead Bushes - Grulag
>     # Missing 'sounds' folder in mod root/gamedata/ found 'textures' folder instead
> 
> 273- Longreed's fixed artefacts spawns under maps - Longreed
>     # Missing 'meshes' folder in mod root/gamedata/ found 'sounds' folder instead
> 
> 274- Dark Signal Audio Pack - Shrike
>     # Missing 'dvl', 'r700aics', 'k98kmod', and 'k98k' folders from mod root/gamedata/Sounds/weapons/_gunfire/mono/
>     # Missing 'aimin', 'aimout', 'ak74', 'ak74m', 'akm', 'aks74u', 'aps', 'bm16', 'cz52', 'generic', 'grach', 'kiparis', 'l85', 'lower',
>     # 'mosin', 'pb', 'pm', 'pmm', 'ppsh41', 'raise', 'rattle', 'remmington870', 'rpk74', 'saiga', 'sks', 'svt40', 'toz194', 'toz34', 'tt33', and 'vz61'
>     # from mod root/gamedata/Sounds/weapons/
> 
> 278- Kar 98 Remodel and Reanimation - JadeyMoyaison
>     # Missing '0.4 Hud' from mod root/
> 
> 283- Autumn No Leaves LOD Fix - owencraig08
>     # 'db' folder installed directly to mod root/ instead of mod root/gamedata/
>     # Missing 'gamedata' folder from mod root/
> 
> 302- Minimalist companion UI moddb - Kageeskl
>     # Mod folder completely missing
> 
> 312- Gunslinger Guns for Anomaly - Teivazcz & Gunslinger Team
>     # Missing 'music' folder from mod root/gamedata/sounds/
> 
> 314- Retrogue's Additional Weapons - Retrogue
>     # Mod folder completely missing
> 
> 33- HD mutant models and textures - Umbrellord
>     # 'db' folder installed directly to mod root/ instead of mod root/gamedata/
>     # Missing 'gamedata' folder
> 
> 34- Nicer Flashlights - shortnamesalex
>     # Missing 'gamedata' folder
> 
> 365- Boomsticks and Sharpsticks 2022 Guns - Mitch & Team
>     # Mod folder completely missing
> 
> 371- FDDA Enhanced Animations - Mirrowel & MFS Team & Gunslinger Team
>     # Missing 'FDDA Enhanced Animations - Food and Drinks 1.2N' folder from mod root/
> 
> 40- Food Drugs and Drinks Animations FDDA - Feel_Fried
>     # Missing 'addons' folder from mod root/
> 
> 55- Mutants Bleeding - Arszi
>     # Mod folder completely missing
> 
> 76- Boomsticks and Sharpsticks New (keep disabled) - Mich
>     # Mod folder completely missing
> 
> 82- Abakan Replacer - Strogglet15
>     # Missing 'patches' folder from mod root/
> 
> 84- Saiga 12K replacer - Strogglet15
>     # Missing 'addons' and 'patch' folders from mod root/
> 
> 86- G36Pack - Strogglet15
>     # Missing 'addons' and 'patch' folders from mod root/
> 
> 88- Dragunov Replacer - Strogglet15
>     # Missing 'addons' and 'patches' folders from mod root/
> 
> 92- Vityaz Replacer Remake - Blackgrowl
>     # Missing 'Default Grip' and 'Original Grip' from mod root/gamedata/
> 
> 94- Tacticool scopes - jaymorrow
>     # Missing 'gamedata' folder from mod root/
> 
> 99- BAS Scopes Extravaganza red dots - Kuez
>     # Missing 'Green' and 'Red' folders from mod root/
> 
> Grulag's Dead Bushes
>     # Folder Completely Missing
> 
> Lifestorock's Bleak Fall Redux Performance
>     # Folder Completely Missing
> 
> Longreed's fixed artefacts spawns under maps
>     # Folder Completely Missing
> 

Additionally here is a screenshot of MO2 after running the script with the #160 fix

![Screenshot_20241023_195943](https://github.com/user-attachments/assets/cf0c90b4-cfdc-4db3-a39d-8ce9b9c07b64)

I'd like to note #160 did fix the missing mods from the zip files @JoelTurtiainen mentioned.

**Comment by Mord3rca** [comment]
Not completed yet

**Comment by Mord3rca** [comment]
* 141 fixed crafting ...
```sh
$ unzip -l v2.6Crafting_With_MultiUse_Items_Fix.zip 
Archive:  v2.6Crafting_With_MultiUse_Items_Fix.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  04-17-2024 03:49   v2.6Crafting_With_MultiUse_Items_Fix/gamedata/
        0  04-17-2024 03:56   v2.6Crafting_With_MultiUse_Items_Fix/gamedata/scripts/
     4171  04-17-2024 04:54   v2.6Crafting_With_MultiUse_Items_Fix/gamedata/scripts/zzz_timsi_ui_workshop.script
      518  04-17-2024 04:23   v2.6Crafting_With_MultiUse_Items_Fix/READ ME BEFORE INSTALLATION.txt
---------                     -------
     4689                     4 files
``` 
GAMMA definition is looking for:
> v2.5Crafting_With_MultiUse_Items_Fix + Patches\Main

* 142 - fixed crafting WPO

Same content as 141
GAMMA defs are looking for:
> v2.5Crafting_With_MultiUse_Items_Fix + Patches\Main + Weapon Parts Overhaul Patch

* 242 - Gardener of The Zone ...
Looking for 3.1 folders where mods is in version 4.6 rn

* 34 - Nicer flashlight

Updated to 2.0 (and looking for 1.9)

* 94 - Tacticool scopes

Updated to 1.6 (looking for 1.4)

------
So for your last screenshot, all defect are caused by a definition issue, see [modpack_maker_list.txt](https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_data/modpack_maker_list.txt). A fix have to by made on Stalker_GAMMA repo to fix this.

**Comment by kalrach** [comment]
Understood, thank you for the help. If all that can be done has been done for script let me know and I'll close the issue.

**Comment by Mord3rca** [comment]
On my side yes ... can't do more ^^"
Now, a fix have to be done on [Stalker_GAMMA](https://github.com/Grokitach/Stalker_GAMMA) to fix the last 5 issues.
