### ISSUE TITLE
Fresh install results in a handful of broken mods

### ISSUE THREAD

**Issue by gardebreak** [Mord3rca/gamma-launcher#163]
After performing a fresh install today there are a handful of mods flagged as broken in MO2:

![Screenshot_20241103_160510](https://github.com/user-attachments/assets/bcea6b01-fe63-4dee-9ed5-ecf49e13b7f2)

Here is a section of the installer output for one of the broken mods (Powered Exos.) All of the broken mods say something similar.

```
[+] Installing mod: Powered Exos ExoServomotorSounds patch
Extracting /data/games/stalker-gamma/downloads/latest.zip
    Installing exo servo patch -> /data/games/stalker-gamma/mods/48- Powered Exos ExoServomotorSounds patch - arti
    WARNING: exo servo patch does not exist
[+] Installing mod: Powered Exos
Extracting /data/games/stalker-gamma/downloads/latest.zip
    Installing anomaly-exo-latest -> /data/games/stalker-gamma/mods/47- Powered Exos - arti
    WARNING: anomaly-exo-latest does not exist
```

Browsing to the Powered Exos directory (`stalker-gamma/mods/47- Powered Exos - arti`) there is nothing there except `meta.ini`. Looks as if there is some issue with downloading and/or extracting these particular mods?

**Comment by Mord3rca** [comment]
Hey !

Looks like a duplicate of #158 , please use pip installed version of this program targeting master branch.

**Comment by gardebreak** [comment]
Running latest from `master` worked. Still results in a few broken mods but as you say in the other issue there is a problem with those mod definitions in the GAMMA repository. Thanks!
