### ISSUE TITLE
Fails on Updating G.A.M.M.A. Definition step

### ISSUE THREAD

**Issue by dhasial** [Mord3rca/gamma-launcher#171]
Commit 73cfa23c
Command: `gamma-launcher full-install  --anomaly ~/Games/fastergames/Anomaly --gamma ~/Games/fastergames/GAMMA --cache-directory ~/.cache/gammacache`
Output: https://gist.github.com/dhasial/731b016f5257848fa86d5a030a08afa6

**Comment by Mord3rca** [comment]
Looks to be a duplicate of #161 and this is a network error

Try to clone the repository somewhere else with `git`, if it's still failing. Not a launcher issue.

Command to exec: `git clone https://github.com/Grokitach/Stalker_GAMMA.git`

**Comment by dhasial** [comment]
How can I tell the script where the cloned repo is? Or maybe it has a default location I could put it in

**Comment by Mord3rca** [comment]
It will be cloned in **<path/to/gamma>/downloads** but this is not the point of this test. Clone it elsewhere :)

**Comment by dhasial** [comment]
Alright it did manage to fully install after doing that. 

(I'm still getting unhandled exceptions when launching because it supposedly doesn't have enough memory with nearly all of 32GB free, but I'm pretty damn sure that's not launcher-related.)

**Comment by Mord3rca** [comment]
If this kind of issue are getting back, use `GAMMA_LAUNCHER_NO_GIT=1` env variable so it won't use `git` subsystem and fallback to archive download.
