### ISSUE TITLE
FileExistsError on GAMMA update to 0.9.3

### ISSUE THREAD

**Issue by MichaelHochriegl** [Mord3rca/gamma-launcher#176]
Greetings,

I tried to update my Gamma install to the newly released version 0.9.3, however I'm facing this error:
```Extracting /home/drcox1911/Games/Gamma/drive_c/GAMMA/downloads/Catspaw_Milspec_PDA-1.14.1.zip
Traceback (most recent call last):
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/lib64/python3.13/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/lib64/python3.13/site-packages/launcher/commands/install.py", line 304, in run
    self._install_mods()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/lib64/python3.13/site-packages/launcher/commands/install.py", line 253, in _install_mods
    mod.install(self._mod_dir)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/lib64/python3.13/site-packages/launcher/mods/installer/default.py", line 68, in install
    with DefaultTempDir(self, prefix="gamma-launcher-modinstall-") as pdir:
         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/lib64/python3.13/site-packages/launcher/mods/tempfile.py", line 49, in __enter__
    getattr(self, hotfix)(s)
    ~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/drcox1911/Games/Gamma/drive_c/gamma-launcher-git/env/lib64/python3.13/site-packages/launcher/mods/tempfile.py", line 32, in _post_decompression_hotfix_00_malformed_archive
    p.parent.mkdir(parents=True, exist_ok=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/pathlib/_local.py", line 722, in mkdir
    os.mkdir(self, mode)
    ~~~~~~~~^^^^^^^^^^^^
FileExistsError: [Errno 17] File exists: '/tmp/gamma-launcher-modinstall-o6ojdkce/00. Milspec PDA with Kill Tracker (required)/gamedata'
```

I'm running Fedora 41 and used the pip-method, so I built the master  branch myself inside the venv.
Is there any other info I could provide for finding a solution?

**Comment by simkej** [comment]
I am having the same issue, same error at the same mod its trying to install

**Comment by Mord3rca** [comment]
Which version of python are you using ?

**Comment by markysayshi** [comment]
I'm having the exact same error, using python 3.12.7. Tried rebuilding/reinstalling gamma-launcher but got same error again.

**Comment by MichaelHochriegl** [comment]
I'm running python 3.13

**Comment by simkej** [comment]
I'm using Python 3.12.7

**Comment by gardebreak** [comment]
Same issue here on Python 3.12.7.

**Comment by Izowiuz** [comment]
Current problem with `_post_decompression_hotfix_00_malformed_archive` function is that it is sometimes moving malformed "folder definitions" as files which in turns blocks proper folder renaming. What we could to sidestep this is to, for example, abuse what we know about such "folders" - their file size appears to be zero.

We could change `_post_decompression_hotfix_00_malformed_archive` from https://github.com/Mord3rca/gamma-launcher/blob/master/launcher/mods/tempfile.py to:

`
    def _post_decompression_hotfix_00_malformed_archive(self, dir: Path) -> None:
        for path in dir.glob('*.*'):
            if '\\' not in path.name:
                continue

            p = dir / path.name.replace('\\', '/')
            p.parent.mkdir(parents=True, exist_ok=True)

            if path.stat().st_size != 0:
                path.rename(dir / p)
`

This is untested and will not work if mods sometime use 0 sized files. `Milspec PDA with Kill Tracker` seemed to install correctly in my case but I have problems installing whole of GAMMA because of failing downloads.

**Comment by Mord3rca** [comment]
Good catch @Izowiuz ! I've created a PR implementing this kind of logic.

It is no longer failing on my side but I did not try to run the game.
Can someone else try #177 and confirm it just works ?

Thanks

**Comment by gardebreak** [comment]
I just tested #177 and it resolves the issue with the "Milspec PDA with Kill Tracker" mod. (However I still don't have a working game--only got 506 of 507 mods in MO2.)

**Comment by markysayshi** [comment]
> I just tested #177 and it resolves the issue with the "Milspec PDA with Kill Tracker" mod. (However I still don't have a working game--only got 506 of 507 mods in MO2.)

I tested it as well, at first I got a location error but deleted/recreated my venv and it worked after. I also have 506 mods but my game is running fine? I was able to start a playthrough. I haven't checked discord to see how many mods should be enabled by default however. I had to restore old user.ltx file (as usual) to get the game to launch.

**Comment by simkej** [comment]
Also tried the fix and it works now, also 506 mods installed, the discord says there should be 507 so not sure if that is another issue but the game works either way.

**Comment by Mord3rca** [comment]
@simkej Without the name of the mods which is not installed. I can't do anything

**Comment by gardebreak** [comment]
I made my `gamma-launcher` install work on Linux by identifying the broken mods and copying them over from an official Windows install. I'll open a new issue a little later with my findings

**Comment by gardebreak** [comment]
See #178
