### ISSUE TITLE
Borked Install 0.9.3

### ISSUE THREAD

**Issue by MichaelHochriegl** [Mord3rca/gamma-launcher#183]
Greetings,

I don't really know if this is happening due to the installer here, but I thought that you all in here are more knowledgeable than me by a mile.

As Grok pushed an update yesterday there should be 506 mods, however I have 507 (don't think that that really matters though, as I was not able to play any update since 0.9.3 came out).

I tried using Bottles, Lutris and manual Wine prefix, however I always crash on first Gamma start with "Unhandled exception occured. See log for details".

When looking in the log I'm not seeing any specific error.
I've attached the log and here is the last bit of it:
```[material_pairs.ltx] Adding new material pair objects\tin_can | objects\grenade, id 1829
stack trace:

 

SymInit: Symbol-SearchPath: '.;C:\Anomaly\bin;C:\Anomaly\bin;C:\windows;C:\windows\system32;', symOptions: 530, UserName: 'steamuser'
OS-Version: 6.2.9200 () 0x0-0x1
C:\Anomaly\bin\AnomalyDX11.exe:AnomalyDX11.exe (0000000140000000
[xray_steamuser.log](https://github.com/user-attachments/files/18048580/xray_steamuser.log)
), size: 18341888 (result: 0), SymType: '-exported-', PDB: 'C:\Anomaly\bin\AnomalyDX11.exe'
at address 0x00006FFFF67BC66A
```

[xray_steamuser.log](https://github.com/user-attachments/files/18048583/xray_steamuser.log)

Hm, the upload doesn't seem to work, so [here](https://pastebin.com/iG4k5fEA) is a pastebin.

**Comment by Mord3rca** [comment]
Hey !
According to repository changes ... it may be related to this commit https://github.com/Grokitach/Stalker_GAMMA/commit/9c57a2b84e59b495ce44cb189bee402bb3dd996c. Can you disable **Frosty's NPC Weapons Reposition** and try again ?

**Comment by MichaelHochriegl** [comment]
Thanks for the quick reply, unfortunately disabling `Frosty's NPC Weapons Reposition` did not fix it, still have the same error message.
```
THM chunk 2072 fixed, wrong size = 21, correct size = 31 [2]
stack trace:

 

SymInit: Symbol-SearchPath: '.;C:\Anomaly\bin;C:\Anomaly\bin;C:\windows;C:\windows\system32;', symOptions: 530, UserName: 'steamuser'
OS-Version: 6.2.9200 () 0x0-0x1
C:\Anomaly\bin\AnomalyDX11AVX.exe:AnomalyDX11AVX.exe (0000000140000000), size: 18284544 (result: 0), SymType: '-exported-', PDB: 'C:\Anomaly\bin\AnomalyDX11AVX.exe'
at address 0x00006FFFF67BC673
```

**Comment by Mord3rca** [comment]
Can you try to reproduce the issue with the official launcher ? With a VM or by using a recent archive from [here](https://all-seer.com/cdn/games/gamma/) (not yet available)

Looks like a definition issue but better be sure. If the official setup works, please make sure to do a `meld` of the two GAMMA mods folder to see what is missing / not correctly installed.

**Comment by alcybersec** [comment]
Hi. I am having the same issue. The game won't launch with "Unhandled exception occured. See log for details" error. I also tried running an anomaly install  verification and it got me this:
`Traceback (most recent call last):
  File "/home/alex/Games/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/alex/Games/gamma-launcher/env/lib64/python3.13/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/alex/Games/gamma-launcher/env/lib64/python3.13/site-packages/launcher/commands/check.py", line 43, in run
    raise RuntimeError(f"Invalid file(s) detected:\n{err_str}")
RuntimeError: Invalid file(s) detected:
/home/alex/Games/Anomaly/bin/AnomalyDX10.exe
/home/alex/Games/Anomaly/bin/AnomalyDX10AVX.exe
/home/alex/Games/Anomaly/bin/AnomalyDX11.exe
/home/alex/Games/Anomaly/bin/AnomalyDX11AVX.exe
/home/alex/Games/Anomaly/bin/AnomalyDX8.exe
/home/alex/Games/Anomaly/bin/AnomalyDX8AVX.exe
/home/alex/Games/Anomaly/bin/AnomalyDX9.exe
/home/alex/Games/Anomaly/bin/AnomalyDX9AVX.exe
/home/alex/Games/Anomaly/bin/soft_oal.dll
`

**Comment by Mord3rca** [comment]
@alcybersec caused by GAMMA patch to Anomaly folder. This is not an issue

**Comment by alcybersec** [comment]
> @alcybersec caused by GAMMA patch to Anomaly folder. This is not an issue

Maybe it is not related, however I am still unable to launch the game as it show "Unhandled exception occured. See log for details" error. I have tried launching in different configurations, but nothing works. Do you have a troubleshoot guide for this issue?

**Comment by MichaelHochriegl** [comment]
Sorry for not answering sooner, but I wanted to try the new hotfixes Grok pushed before setting up a VM and what not, but unfortunately I always run into another error now on downloading Gamma. Guess I will best open another issue to get that one worked out so I can do the `meld`.

**Comment by BoboB4Time** [comment]
Hello,

Some issues I encountered:
-MO shows correct 507 mods, however NicerFlashlights has a red 'X' flag.
-Unhandled Exception occurs, log file is exactly like Michaels "up_fourte_vssk" and others.
-Reinstalling results in the same 'X' next to NicerFlashlights, but this time the crash when launching outputs a log stating "wpn_sig550_leupold" was not specified as an overwrite.

Two days ago, without any change in steps, I was able to install and play the game normally. I encountered crashes in Darkscape; thinking it was a bad install, I deleted and reinstalled only to face the above. Sad thing is, the Darkscape issue was unrelated to the install and a fix can be found in the discord T.T

Please let me know how I can better assist in identifying the issue, and thank you very much for even making this possible for us linux people.

**Comment by Mord3rca** [comment]
Hello,
to identify the issue, you can use option `--custom-gamma-definition` and set it to something else (not master).

If it works on the commit you used with the custom option, create a new install dir with a more recent commit ... And go ahead until it do not work.
Once you have it, `meld` the two installation to find the issue.

Concretely, you will do a binary search / bisection to find the problematic commit. It will be long and tedious but it can work.

Note: Use a cache ... It's way faster this way and you will avoid to trigger ModDB Too Many Requests error code and be locked for 1h.

**Comment by BoboB4Time** [comment]
Hi Mord!
I must preface with the fact that I am new to linux; nevertheless I am eager to learn.

I followed DravenusRex' tutorial on how to use your tool and install. I did try the cache option, however with the command "gamma-launcher full-install --anomaly <anomaly path> --gamma <GAMMA path> --cache-directory <Path>" it simply downloads and installs again. The cache files I used were from his tutorial, sitting unextracted in my Downloads folder. Please advise, thank you.

**Comment by Mord3rca** [comment]
You will have to use `gamma-launcher full-install --anomaly <path/to/anomaly> --gamma <path/to/gamma> --cache-directory <path/to/cache> --custom-gamma-definition <commit hash>`

You can find all commits of Stalker_GAMMA here: https://github.com/Grokitach/Stalker_GAMMA/commits/main/
Hashes are to the right (like 0fe7bb0)

**Comment by BoboB4Time** [comment]
I will do that; starting with the december 9 verified hash '23d38f7563b72c4d7c9ac26ce721302ae332bdad' as that is the same date the game was working.

Thank you, I will report back.

**Comment by BoboB4Time** [comment]
I'm getting a time-out followed by fatal error 'repository <https://github.com/Grokitach/Stalker_GAMMA/archive/571fa31.zip> not found'
I have also tried the command with the full SHA to be met with the same error; e.g:

gamma-launcher full-install --anomaly /home/bobos/Anomaly/ --gamma /home/bobos/GAMMA/ --cache-directory /home/bobos/Downloads/cache/ --custom-gamma-definition 571fa31

&

gamma-launcher full-install --anomaly /home/bobos/Anomaly/ --gamma /home/bobos/GAMMA/ --custom-gamma-definition 571fa31e763161ea1a9cad134e3ec5605032c47f

**Comment by Mord3rca** [comment]
Looks like Stalker_GAMMA repository was not correctly initialized. Probably from a previous command.
Can your remove `<path/to/gamma>/downloads/Stalker_GAMMA.git/` and try again ?

**Comment by JamesMowery** [comment]
I just wanted to report in that I did a fresh install about two or three hours ago and had some issues regarding 3 separate files regarding guns and sights. It caused crashing upon startup. Seems to be an issue specific to Linux.

The Discord thread starts here (and it involves replacing 3 files, so it's easier just to post the Discord so you get them from the source): https://discord.com/channels/912320241713958912/1315449108797980762/1317714898444091392

But a TL;DR:

You need to download these three files:

- [w_sig220.ltx](https://cdn.discordapp.com/attachments/1315449108797980762/1317717567980441690/w_sig220.ltx?ex=675fb39e&is=675e621e&hm=73b6087e02ec6219329a3a6ccbd5e0037f71a51a17fa0a8e8aa6b5ade78a812e&)
- [w_sig550.ltx](https://cdn.discordapp.com/attachments/1315449108797980762/1317717568487817216/w_sig550.ltx?ex=675fb39e&is=675e621e&hm=8e9fc7f013ff7b3d74f89965d952f7a90a06d751d5a9426b3897f7b7370c015e&)
- [w_sig552.ltx](https://cdn.discordapp.com/attachments/1315449108797980762/1317717568940937298/w_sig552.ltx?ex=675fb39e&is=675e621e&hm=1b67dc5a92536a50230fee9af803c0e4c4c681c59210747b436999b9ff669016&)
13.78 KB

Then place them into: `/GAMMA/mods/312- Gunslinger Guns for Anomaly - Teivazcz & Gunslinger Team/gamedata/configs/items/weapons/`

That fixed the issue for me.

**Comment by Mord3rca** [comment]
Apparently this is fixed after a clean install (see #189), can someone confirm ?

**Comment by gnusenpai** [comment]
I just reinstalled and nothing has changed. Same `Duplicate section 'wpn_sig550_leupold'` crash.

**Comment by JamesMowery** [comment]
> Apparently this is fixed after a clean install (see #189), can someone confirm ?

On that Discord thread I mentioned above, it was suggested that gamma-launcher is not actually downloading the latest updates correctly. To be clear: I have absolutely no idea if that's true or not

But if @gnusenpai just did a fresh install, and there's still an issue, perhaps there is something wrong with it not grabbing the latest versions?

**Comment by Mord3rca** [comment]
#191 will fix the issue.

Commit message explain why this was happening if you are curious.

**Comment by JamesMowery** [comment]
Amazing.

I probably won't be able to test this, as I'm running very low on disk space since I also got Stalker 2 installed, but I'll give an upgrade a go once Grok releases another big update! Appreciate you, as always, @Mord3rca!

**Comment by MichaelHochriegl** [comment]
> #191 will fix the issue.
> 
> Commit message explain why this was happening if you are curious.

I just gave this one a go and it seems its working.

**Comment by Mord3rca** [comment]
@MichaelHochriegl Thanks for confirming !
