### ISSUE TITLE
a bit of a nub here...

### ISSUE THREAD

**Issue by mak10z** [Mord3rca/gamma-launcher#187]
Greetings all,

Trying to install the latest gamma-launcher in endeavourOS and running in to this error.  

* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'

ERROR Backend 'setuptools.build_meta' is not available.

I had v. 2.1 installed, but I run across this every time I try to build 2.2   
I verified that all the dependencies are installed. 

(+depends=(python python-bs4 python-platformdirs python-py7zr python-unrar python-requests python-tenacity python-tqdm python-magic python-rarfile python-gitpython python-cloudscraper)
+makedepends=(git python-pip python-build python-installer python-wheel)
+optdepends=(unrar)

any assistance would be appreciated.
python version is showing as Python 3.12.7

Thanks in advance :)
-Mak

edit:  I get this if I clone the git, and if I use the YAY installer

**Comment by Mord3rca** [comment]
Hello,

It seems you are using AUR installation method, please contact AUR package maintainer here: https://aur.archlinux.org/packages/gamma-launcher

**Comment by mak10z** [comment]
I get the same message if I use the AUR or if I clone the git
