### ISSUE TITLE
'pip install .' failing with spaces in a path

### ISSUE THREAD

**Issue by axet** [Mord3rca/gamma-launcher#23]
Hello!

Using space in top game folder (example "S.T.A.L.K.E.R. GAMMA") causing gamme-launcher failed to start with error:

    cannot execute: required file not found

'pip install .' will create incorrect 'env/bin/gamma-launcher' with shebang pointing to python3 with space in a path.

This is know limitation of shebang - it does not support spaces / escape symbols (as far as I know).

I'm not python guy. Probably here should be some 'pip install' options to solve that.

**Comment by Mord3rca** [comment]
```sh
$ gamma-launcher -h
zsh: /tmp/.test venv/bin/gamma-launcher: bad interpreter: "/tmp/.test: no such file or directory
```

Better avoid spaces, this is a shebang limitation. I don't think there is a pip fix for this one.

**Comment by axet** [comment]
'pip install' can use system intepretator instead of venv with space in a path.

**Comment by axet** [comment]
I guess this is a pip bug: https://stackoverflow.com/questions/15472430/using-virtualenv-with-spaces-in-a-path

changing env/bin/gamma-launcher to:

#!/usr/bin/env python3

make it work

**Comment by axet** [comment]
this is not related to the #24

**Comment by Mord3rca** [comment]
Indeed, but this is a tool issue related to `pip` and I have 0 control over it

**Comment by axet** [comment]
That is correct sequince to install:

```
pip install -qU pip
 pip install --no-cache .
```

Which producing correct working binaries.

**Comment by axet** [comment]
Thanks! pip-23.1.2 working fine!
