### ISSUE TITLE
Consider adding releases to gamma-launcher

### ISSUE THREAD

**Issue by robertharris-xyz** [Mord3rca/gamma-launcher#25]
This is less of an issue and more of a request/suggestion. Understandably, this project is currently under active development at the moment, but making directly downloadable executables of the gamma launcher under Releases may save a lot of headaches from users and people answering issues in the future. There will probably be users downloading this that might not be familiar with Python and its nuances, so might find the current installation process complicated. Releases of gamma-launcher would hopefully cut down on the complexity for users and, in turn, the number of reported issues.

**Comment by Mord3rca** [comment]
I'll see what I can do with `pyinstaller` and Github Workflow to generate an executable

**Comment by Mord3rca** [comment]
Workflow did not trigger but .... I've generated the executable on my side. Can you take a moment to test it ?

https://github.com/Mord3rca/gamma-launcher/releases/tag/v1.0

**Comment by robertharris-xyz** [comment]
I've tested the `check-md5` and `full-install` commands against my current installation of GAMMA and it worked.
