### ISSUE TITLE
Document all parameters

### ISSUE THREAD

**Issue by Singustromo** [Mord3rca/gamma-launcher#33]
Hello, thanks for your work. It helps immensely.
While getting acquainted with your script I noticed that some useful parameters are not documented:

- [ ] check-md5:  --redownload
- [ ] install: --no-def-update --no-anomaly-patch --preserve-user-config

**Comment by Mord3rca** [comment]
Hello,

If you are talking about **README.md**, this is normal, it only list common use case.
To view all options for a command use:
`gamma-launcher <command> --help`

**Comment by Singustromo** [comment]
Thanks for the quick reply. Seems that it is no necessary then :)
