### ISSUE TITLE
Target mod folders are cluttered

### ISSUE THREAD

**Issue by Singustromo** [Mord3rca/gamma-launcher#34]
For demonstration purposes I have used **usvfs-workaround**:

![030623-1685792280_scrot](https://github.com/Mord3rca/gamma-launcher/assets/68005562/ffc25d60-43bc-4ba6-9b82-c46630178657)

### Possible Solution
only copy following subfolders:
1. appdata
2. gamedata
3. bin
4. db

## Reasoning
The resulting mod folders take up less disk space in the end

**Comment by Mord3rca** [comment]
I agree on principle but ModOrganizer do not do that since it does not know how STALKER works.

However, I can add a command option to do so... And it will maybe be better to add this in the **full-install** command. Some testing is required.

**Comment by Singustromo** [comment]
It seems that Groks Installer is doing it. I have not noticed these additional folders when I used the proprietary launcher from grok.
I'd like to help but my proficiency lies within bash. I am happy to test new versions, though.

**Comment by Mord3rca** [comment]
Are you sure ? I've just booted my Win10 VM and executing the Virtual Expolrer. **0.4 HUD** exists.
![Screenshot_2023-06-03_16-46-34](https://github.com/Mord3rca/gamma-launcher/assets/25133280/c9801072-e743-49d7-9393-e75ef7a0ef3e)

This was generated 2 months ago, was an updated of Grok's launcher released with this feature ?

I can still filter interesting data

**Comment by Singustromo** [comment]
Looks like my answer sent via e-mail did not come through. Should be visible as an answer.
You are right about these 4 folders and the loose files in the anomaly root directory. This installer though clutters the anomaly root directory far more. My screenshot shows **40 additional folders** overall.

**Comment by Mord3rca** [comment]
Reinstalling all mods with the modification made in the PR make a really clean install folder :ok_hand: 

Just rm all mods, rerun `full-install` and `usvfs-workaround`
```sh
rm -rf <path/to/gamma>/mods/*
gamma-launcher full-install --anomaly <path/to/anomaly> --gamma <path/to/gamma>
gamma-launcher usvfs-workaround --anomaly <path/to/anomaly> --gamma <path/to/gamma> --final <path/to/final/install>
```

**Comment by Singustromo** [comment]
That's great. I would like to try it but honestly... I do not know how to compile this into one executable or how to even run it at all in this state.

**Comment by Mord3rca** [comment]
Release for testing: https://github.com/Mord3rca/gamma-launcher/releases/tag/pr-test

**Comment by Singustromo** [comment]
Works very well, thanks you :)
Thanks to an explanation in one of your repos I can now directly use it from the source with
`pip install .`
