### ISSUE TITLE
usvfs-workaround: fix paths

### ISSUE THREAD

**Issue by Singustromo** [Mord3rca/gamma-launcher#35]
![030623-1685791869_scrot](https://github.com/Mord3rca/gamma-launcher/assets/68005562/390d0c66-7c2f-42aa-84ac-53afa34889ea)

Due to the very nature of *nix being case-sensitive the resulting gamedata folder contains non-merged folders with different capitalization. The picture demonstrates this very well. This happens throughout the gamedata-folder, resulting in in-game glitches and bugs (Noticeably the sound -> TOZ-34 for example).

Wine, as of now, does not seem to handle this:
https://wiki.winehq.org/Case_Insensitive_Filenames

## Possible solution
Rewrite paths to be lowercase before copying.
For this another library must be used or a function needs to be written from scratch

**Comment by Singustromo** [comment]
Alternatively the function distutils.dir_util.copy_tree(..) can be replaced with a modified version via monkey patching.
I don't know though where to find said function from distutils. There's also a probability that it was written in C.

**Comment by Singustromo** [comment]
Another way is to write a function that will be executed on the target mod directory and renames the folders to their lowercase counterpart.

**Comment by Mord3rca** [comment]
It's not possible with folder filtering

I was planning on lowering everything just before but ... It's not a solution since some installation directives contain capital letters.
Still looking for a smart idea to do that. Actually, the only mod with capital letters is: **122- Zone Tales in Loading Screens - Oni**, so issue is really minor.

I may need to search for **gamedata** dirs in decompressed archive and force them to lowercase.

**Comment by Singustromo** [comment]
> It's not possible with folder filtering
> 
> I was planning on lowering everything just before but ... It's not a solution since some installation directives contain capital letters. Still looking for a smart idea to do that. Actually, the only mod with capital letters is: **122- Zone Tales in Loading Screens - Oni**, so issue is really minor.
> 
> I may need to search for **gamedata** dirs in decompressed archive and force them to lowercase.

I got a little bit acquainted with python and wrote a recursive function that does what we need. The initial folder will not be renamed (The mod folder).
```python
# path to mod directory
def tree_lower_directories(directory, level = 0):
    if not os.path.lexists(directory): return False
    
    if level > 0 and any(map(str.isupper, os.path.basename(directory))):
        ps = os.path.split(directory)
        os.rename(directory, os.path.join(ps[0], ps[1].lower()))
        directory = os.path.join(ps[0], ps[1].lower())

    for inode in os.listdir(directory):
        if os.path.isdir(os.path.join(directory, inode)):
            tree_lower_directories(os.path.join(directory, inode), level +1)
```

**Comment by Singustromo** [comment]
I used it separately in the mods folder. Works as intended :)
The game glitches I observed are solved

**Comment by Mord3rca** [comment]
PR should fix the issue, you can check that by verifying the content of mod 122

**Comment by Singustromo** [comment]
> PR should fix the issue, you can check that by verifying the content of mod 122

Great you made that. Why do you not use my code, though?
It has less dependencies, as you are already using shutil.

**Comment by Mord3rca** [comment]
I prefer to avoid recursive function and using `pathlib` instead of `os` since it is used everywhere in this code

**Comment by Singustromo** [comment]
Okay, fair enough.
