### ISSUE TITLE
Updating from 0.9 to 0.9.1 requires manually deleting GAMMA_definition.zip

### ISSUE THREAD

**Issue by wildfield** [Mord3rca/gamma-launcher#59]
If I already have a 0.9 install, I need to delete GAMMA_definition.zip for it to actually update the modpack list, otherwise it uses cached version of it

**Comment by Mord3rca** [comment]
PR created, can you confirm it resolve the issue ?

**Comment by wildfield** [comment]
--update works, thanks. 

As a suggestion, maybe it's also possible to check against latest commit by doing curl https://api.github.com/repos/Grokitach/Stalker_GAMMA/branches/main. This doesn't need a token or git dependency

**Comment by Mord3rca** [comment]
PR updated, local & remote version are checked. If remote version is > to local version, package is updated.

To check this, edit **version.txt** file in Grok's directory to be lower than remote file (G.A.M.M.A._definitition_version.txt)

**Comment by wildfield** [comment]
I've checked, works well. Nice
