### ISSUE TITLE
Needing to manually delete GAMMA definition for hotfixes to apply

### ISSUE THREAD

**Issue by 0xC0ncord** [Mord3rca/gamma-launcher#61]
I might be doing something wrong, but each time a hotfix for GAMMA is released I have been needing to manually delete the `GAMMA_definition.zip` in the `.Grok's Modpack Installer/` directory. If I run a full install without doing this, the first thing I notice is that within Mod Organizer 2, the count of active mods does not match what it should be (e.g. 415 active versus 416 what it should be).

**Comment by Mord3rca** [comment]
Hello, this was fixed in #60 , please use the master branch and try again

**Comment by 0xC0ncord** [comment]
> Hello, this was fixed in #60 , please use the master branch and try again
> 

Sure, I'll make sure to try `-master` the next time a hotfix comes out and reply back to this issue.

> Also, which mod is not installed ?

For the last hotfix, it was "Show number of items in your possession before tasking tasks"

**Comment by Mord3rca** [comment]
I can't reproduce it, I have 416 mods active on GAMMA version 814:
![image](https://github.com/Mord3rca/gamma-launcher/assets/25133280/19c27dbc-94bb-469b-b4be-efa54157d100)

**Comment by 0xC0ncord** [comment]
> I can't reproduce it, I have 416 mods active on GAMMA version 814: ![image](https://user-images.githubusercontent.com/25133280/271815223-19c27dbc-94bb-469b-b4be-efa54157d100.png)

Before the last hotfix there were 415 mods, but updating without deleting `GAMMA_definition.zip` still left me with only 415 mods active. Only after deleting the definition zip and doing a full install would get me to 416 active mods.

**Comment by Mord3rca** [comment]
Hello @0xC0ncord ,
Gamma definition has been updated to 815, can you try the update mechanism of master ?
Thanks

**Comment by 0xC0ncord** [comment]
> Hello @0xC0ncord , Gamma definition has been updated to 815, can you try the update mechanism of master ? Thanks

I waited until the latest update which added a mod or two so that I know it's working for sure. Gamma definition 819 added several new mods which were all installed successfully, so the problem is indeed fixed. Thanks!

**Comment by ConvexTlc97** [comment]
What is the command you would use to update? what is -master? be nice if the documentation had these things for dummies like me. 

Thanks.

**Comment by 0xC0ncord** [comment]
> What is the command you would use to update? what is -master? be nice if the documentation had these things for dummies like me.
> 
> Thanks.

If you download the ZIP of the code from the homepage, you can get the `-master` version from the time which you download it:
![image](https://github.com/Mord3rca/gamma-launcher/assets/8011001/0b79c574-c415-4d5b-beca-7ac24d97a206)
