### ISSUE TITLE
What is the Command to update Gamma? 

### ISSUE THREAD

**Issue by ConvexTlc97** [Mord3rca/gamma-launcher#67]
Not sure where else to ask this since there is not documentation on what the command is the update gamma. Is it just running full install over again or something else? 

Thanks.

**Comment by Mord3rca** [comment]
Hello,
Just rerun `full-install` and it should update gamma definition itself (be sure to use master branch for this, self contained executable do not have this feature yet)

**Comment by ConvexTlc97** [comment]
Will there a be self contained exe of sorts that works on linux anytime soon?

**Comment by ConvexTlc97** [comment]
Also the full install seems to be broken now. 

`gamma-launcher full-install --anomaly '/home/tc/Games/Anomoly/Anomaly-1.5.1.2/' --gamma '/home/tc/Games/Anomoly/GAMMA RC3/'
`

Seems to hang and not execute the command to update Gamma when entered. the terminal seems to almost hang but does not become unresponsive.

**Comment by Mord3rca** [comment]
> Will there a be self contained exe of sorts that works on linux anytime soon?

Once enough feature will be in the exec. Probably after support of git install mentioned in #68

**Comment by itsryzor** [comment]
Can you update the release? Currently, it installs the old version of GAMMA with 422 mods, even if I force update the modpack_maker_list.txt.

**Comment by Mord3rca** [comment]
@itsryzor here you go: https://github.com/Mord3rca/gamma-launcher/releases/tag/v1.5

**Comment by itsryzor** [comment]
Thanks king.

**Comment by JamesMowery** [comment]
Just wanted to say thanks. Wasn't able to get GAMMA working on Linux for the past few weeks, and have been wanting to try the game. After the 1.5 update, it appears to be working finally!

**Comment by ConvexTlc97** [comment]
> Just wanted to say thanks. Wasn't able to get GAMMA working on Linux for the past few weeks, and have been wanting to try the game. After the 1.5 update, it appears to be working finally!

Wish I could say the same, tried updating it the same as always and didn't work and trying to reinstall the launcher on the 1.5 update doesn't work at all anymore. only 50 mods actually downloaded.

**Comment by Mord3rca** [comment]
Is this issue still relevant ?

**Comment by Mord3rca** [comment]
No user feedback, closing
