### ISSUE TITLE
Git support for upcoming updates

### ISSUE THREAD

**Issue by suchacomic** [Mord3rca/gamma-launcher#68]
Gamma large files, Gunslinger and BAS are going to be downloaded and updated through a git client rather than downloading a tarball from Github, this might break the launcher. 
[Commit 1](https://github.com/Grokitach/Stalker_GAMMA/commit/7bf73b1fdcce1ebc515c9b6160a94fb1cd429b6f)
[Commit 2](https://github.com/Grokitach/Stalker_GAMMA/commit/ec1b32ea359aa1d1c919eba15e80e4bee915202c)

**Comment by Mord3rca** [comment]
Hello, thanks for the notification.

Just made a PR, can you test it on the dev2 branch ?

**Comment by Mord3rca** [comment]
PR #83 should manage this new installation method.

However, can't run GAMMA exec, I have some faulty page and wine stop the exec.
Since this [commit ](https://github.com/Grokitach/Stalker_GAMMA/commit/7bf73b1fdcce1ebc515c9b6160a94fb1cd429b6f) is now on main, somebody can test the fix ?

**Comment by a-camargo** [comment]
ran the launcher from #83 and still got 442 mods (should be 446) and game crashes on start.

**Comment by Mord3rca** [comment]
What are the 4 missing mods ?

Game crash may be related to wine ... Still investigating

**Comment by a-camargo** [comment]
I will check which are missing. However, I failed to mention that this 442 count was the same I was getting with the "old code" from master.
It is really strange though as your new code is indeed downloading what I assume was missing before :thinking:

Yes, the game crashing might be related to the new binaries they've pushed. I'm a little skeptical about that though, it seems to me it's related to missing mods.

**Comment by a-camargo** [comment]
Comparing my `modlist.txt` with [Grok's](https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_data/modlist.txt), these are missing:
-Petrenka's Improved Russian Translation
-Tiskar's & Burn's Attachment Alignment Fixes
+Boomsticks and Sharpsticks 2022 Guns
+Burn's Optimised World Models
+DarkasleQif's and iTheon's Parts Condition Color Thresholds Changes
+G.A.M.M.A. Large Files
+G.A.M.M.A. Vehicles in Darkscape (there are 2 entries in Grok's, mine has 1)
+Retrogue's Additional Weapons

**Comment by Mord3rca** [comment]
> I will check which are missing. However, I failed to mention that this 442 count was the same I was getting with the "old code" from master.

This should fix the issue: https://github.com/Mord3rca/gamma-launcher/commit/c6971d5c1349db00e4a8c71469f7509775fbd1d2 - 445 mods installed after testing
