### ISSUE TITLE
Error messages outputted during full-install command

### ISSUE THREAD

**Issue by robertharris-xyz** [Mord3rca/gamma-launcher#8]
Performing a full install command appears to miss some of the mods in the installation. The `full-install-error.txt` file contains the log produced. `cat full-install-error.txt | grep ERROR` outputs:

```
ERROR: Combat Behavior/Xenotech, Seryoga, Gonta, Crab, Garmata, Pilot, Tourist combat behavior  do not exist
ERROR: Lsz/2_Addons/21_Lsz_Ai_Tweaks do not exist
ERROR: GAMMA Massive Text Overhaul Project (GMTOP) v1.4.1/Required Files do not exist
ERROR: 02 - [OPTIONAL] RESHADE SR - Film Reshade do not exist
ERROR: 02 - [OPTIONAL] RESHADE SR - Film Reshade/bin do not exist
ERROR: gamma_large_files_v2-main/Retrogue's Additional Weapons do not exist
ERROR: 01 Reposition do not exist
ERROR: More_Portrait_Icons do not exist
ERROR: V2 - Rustiest.zip do not exist
ERROR: Aug Augmented Source File/addons/Mags Patch do not exist
ERROR: RE-SOUND BLINDSIDE ANIMS BY YUNGPR1NCE_DLTX do not exist
ERROR: RE-SOUND BLINDSIDE ANIMS BY YUNGPR1NCE_DLTX_Patch_BaS do not exist
ERROR: ABF/ABF/ABF ) ARX - Module 2 - Anomalies + Actor + Poltergeist do not exist
ERROR: ABF/ABF/ABF ARX -- Tweaks/3. Poltergeist harder do not exist
ERROR: ABF/ABF/ABF ARX -- Compatibility/Soundscape Burer Compatibility do not exist
ERROR: dyn tasks do not exist
ERROR: CrashesToRiches/scripts do not exist
ERROR: Stealth_2.0 do not exist
ERROR: [1.1.0] Grok's Better Sound for Anomaly 1.5.1/bin do not exist
```

Running the `check-md5` command produces the log in the `check-md5-error.txt` file. Error output:

```
Error: MagsRedux.2023.01.29.zip not found on disk
Error: Fluid_relations_1.0.7z -- remote(b0827d88e23813173aebd0cbf610b32c) != local(0996e27c341f73dcbb92994df979ed55)
Error: parsing failure for https://www.moddb.com/mods/stalker-anomaly/addons/quick-companion-teleport-151
Error: disable_burnt_fuzz.1.7z -- remote(836f215607182cf60f56f988d0fbe769) != local(067482712ed495fa0279dae9b90bafc1)
```

Beyond this, to get GAMMA to work, I needed to disable these mods:

- 185- Shader Driven Scopes - CrookR
- 186- Shader Driven Scopes BAS patch - CrookR

This may not necessarily be related to this repository however...

I was able to boot into a new game despite these errors, but I'm unsure if they may cause issues later down the line or not - I'm assuming that these mods are not being correctly installed by `gamma-launcher`?

[check-md5-error.txt](https://github.com/Mord3rca/gamma-launcher/files/11360221/check-md5-error.txt)
[full-install-error.txt](https://github.com/Mord3rca/gamma-launcher/files/11360222/full-install-error.txt)

**Comment by Mord3rca** [comment]
All those errors are more warnings, in the official launcher I suspect them to be silently ignored.
This come from the GAMMA definitions and if a mod is upgraded, they can become irrelevant.

Regarding the `check-md5` command, *Fluid_relations_1.0.7z* & *disable_burnt_fuzz.1.7z*
are in the *GAMMA_addons_downloads.7z* archive and so, they are not updated.
```sh
$ 7z l ~/Downloads/GAMMA_addons_downloads.7z | grep disable            
2022-04-01 22:44:45 ....A         1814               downloads/disable_burnt_fuzz.1.7z
$ 7z l ~/Downloads/GAMMA_addons_downloads.7z | grep relations
2022-04-01 22:50:42 ....A         9842               downloads/Fluid_relations_1.0.7z
```
For *MagsRedux.2023.01.29.zip*, you're in luck ! This mod is disabled by default.

So here what I can do to fix this:
* printing a WARNING instead of an Error
* Adding an argument to `check-md5` / `full-install` to force re-download if remote md5 does not match local md5

However, for this: https://www.moddb.com/mods/stalker-anomaly/addons/quick-companion-teleport-151, it's a ModDB issue. Can't parse what do not exist :)
It's probably replaced by https://www.moddb.com/mods/stalker-anomaly/addons/quick-companion-teleport-152 but this need to be fixed in the GAMMA definitions

**Comment by robertharris-xyz** [comment]
Ah I see. Thanks for your input. As for your fix, I may try implementing this myself and send over a PR to help out. Unless this is something you would prefer to do yourself?

**Comment by Mord3rca** [comment]
You can do both if you want to. Add the argument for `check-md5`, since on the official launcher, full install is downloading only if the file do not exist

**Comment by robertharris-xyz** [comment]
After some experimentation, I believe with the current way the archives are downloaded, MD5 hashes will never match even when they are redownloaded with the same method.

Your code reads the `modpack_maker_list.txt` file for downloading and checking the MD5 hash. Using Fluid Relations as an example:

```
https://www.moddb.com/addons/start/209072	0	 - Favkis_Nexerade	 Fluid Relations	https://www.moddb.com/mods/stalker-anomaly/addons/fluid-relations-v10
```

The first link is used to download the archive, and the second link is used to read the HTML page for the correct MD5 value. However if you download both files from each of these URLs, you find that the hashes for both of these files are actually different after all. This means it doesn't really matter if a redownload is performed on the first link again, because it will never actually match the contents of the HTML page. So, for this scenario at least, a redownload will not resolve the problem.

**Comment by Mord3rca** [comment]
I think this is normal .... Download link from https://www.moddb.com/mods/stalker-anomaly/addons/fluid-relations-v10 is `ID: 187930` and provided in `ID: 209072` ... 
Looks like the right URL is: https://www.moddb.com/mods/stalker-anomaly/addons/yastin-favkis-fluid-dynamic-relations ... So the error is upstream for this one :)

**Comment by robertharris-xyz** [comment]
Agreed. I guess if the official developers are using the same definitions, then these inconsistent hashes would be an issue for them too!

**Comment by Mord3rca** [comment]
This should do it ... And I think it should also be in `test-mod-maker` command
https://github.com/Mord3rca/gamma-launcher/commit/c94552938037f197a3054aa51e66a95656c44191

**Comment by Mord3rca** [comment]
Closing since PR is merged
