### ISSUE TITLE
Parse error during check-md5 command

### ISSUE THREAD

**Issue by JackHack96** [Mord3rca/gamma-launcher#80]
Yesterday I've tried updating the gamma-launcher because Grok released an update. Now GAMMA doesn't load anymore even after having performed a fresh install, it just crashes.

So I tried to run the check-md5 command to see if I was missing something and it seems to fail upon parsing the URL of gamma_large_files_v2. I'm attaching the output.

[log.txt](https://github.com/Mord3rca/gamma-launcher/files/13760030/log.txt)

**Comment by Mord3rca** [comment]
Mod installation mechanism changed for some entry (see #68)

Currently working on it

**Comment by Mord3rca** [comment]
Please try again with modification #83

**Comment by JackHack96** [comment]
I've tried again, now I no longer get Python errors so I guess this issue can be closed, but the installation is still not right, as I see 445 mods instead of 446 after a clean install and the game still crashes at startup.

**Comment by Mord3rca** [comment]
Missing mod is: Furniture Hideout Extended (not critical for running GAMMA)
Already identified: https://github.com/Mord3rca/gamma-launcher/issues/88#issuecomment-1872980288. Need to do a fix for this.

For the crash, I've used official launcher v6, try to run GAMMA and it crash. It seems to be related to the update of bin/Anomaly*.exe

**Comment by Mord3rca** [comment]
Using master branch of launcher use definition **59254c2e9432524818cf860eead0deb8ee13f610** of Stalker GAMMA
`gamma-launcher full-install --anomaly /opt/games/WORK/Anomaly --gamma /opt/games/WORK/GAMMA --custom-gamma-definition 59254c2e9432524818cf860eead0deb8ee13f610`

You will have to apply a XML fix to avoid a crash when opening the inventory:
```sh
# In GAMMA directory
cp 'mods/165- Hunger Thirst Sleep UI htsb knifebinoc patches - xcvb/gamedata/configs/ui/ui_new_bars_16.xml' 'mods/164- Hunger Thirst Sleep UI 0.71 - xcvb/gamedata/configs/ui/ui_new_bars_16.xml'
```

**Comment by JackHack96** [comment]
Interesting, doing the installation with that git ref makes the game work unless I change the sunlight settings.

Thanks for the assistance.
