### ISSUE TITLE
extracting error

### ISSUE THREAD

**Issue by Tune45** [Mord3rca/gamma-launcher#81]
Hi.i'm EndeavourOS user .CPU= Intel® Xeon® CPU E3-1270 V2 GPU= AMD RX 580 RAM= 16 GB  kernal=6.6.8-zen1-1-zen (64-bit)
DE= KDE Plasma 5.27.10

i got this 
 ./gamma-launcher full-install --anomaly ~/Games/Anomaly/ --gamma ~/Games/GAMMA/
[+] Installing base Anomaly 1.5.1
Calculating hash of Anomaly-1.5.1.2.7z: 100%|#######################################################################################| 8.75G/8.75G [00:13<00:00, 696MiB/s]
  - Using cached Anomaly-1.5.1.2.7z (0ee1e9a0e45c529536370ba76b0ec47f)
  - Extracting
sh: symbol lookup error: sh: undefined symbol: rl_trim_arg_from_keyseq
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/install.py", line 404, in run
  File "launcher/commands/install.py", line 100, in run
  File "launcher/commands/install.py", line 85, in _install_component
  File "launcher/archive.py", line 57, in extract_archive
  File "launcher/archive.py", line 45, in _7zip_bcj2_workaround
RuntimeError: 7z error will decompressing /home/tune/Games/Anomaly/Anomaly-1.5.1.2.7z
[5347] Failed to execute script 'gamma-launcher' due to unhandled exception!

**Comment by Mord3rca** [comment]
Hello,
```sh
sh: symbol lookup error: sh: undefined symbol: rl_trim_arg_from_keyseq
```
Apparently, `/bin/sh` can't be executed

**Comment by Mord3rca** [comment]
Can you try again with libreadline preloaded ?

`LD_PRELOAD=<path/to/sys/readline.so> ./gamma-launcher ....`

Or by installing launcher in a venv

**Comment by consumptionof** [comment]
> Can you try again with libreadline preloaded ?
> 
> `LD_PRELOAD=<path/to/sys/readline.so> ./gamma-launcher ....`
> 
> Or by installing launcher in a venv

On Arch, preloading libreadline.so got it to work.

**Comment by Mord3rca** [comment]
Root cause: pyinstaller package is done on Ubuntu:latest and contain Ubuntu's libraries.

Resolution: Use pip installation if distro != Ubuntu
