### ISSUE TITLE
modpack_maker_list.txt install_directives not identified properly

### ISSUE THREAD

**Issue by maybeZion** [Mord3rca/gamma-launcher#88]
I believe this is the issue causing missing data in Hideout Furniture Expansion. In mods/\_\_init__.py, line 16, mod instructions are being separated by tab (\t), but in line 349 of modpack_maker_list.txt of GAMMA, there is no tab to separate the author name, but only a few spaces. Should be an easy fix, but it might be easier to convince Grok to reupload the file with a tab hahaha. https://github.com/Grokitach/Stalker_GAMMA/blob/b16e106d5040d35fd5c3c507b82b4d27d567249b/G.A.M.M.A/modpack_data/modpack_maker_list.txt#L349

**Comment by Mord3rca** [comment]
The issue is more complex for this one.

My launcher is looking for gamedata dir... And it is not the case for this one since the fomod script add some install instruction. Since nothing is detected, mod folder is empty.
