### ISSUE TITLE
Launcher produces not working GAMMA install

### ISSUE THREAD

**Issue by sobkas** [Mord3rca/gamma-launcher#89]
Starting with 52004a05d95ea030447e034b71af0aae7542853d(GAMMA) launcher producing not working GAMMA install
Reproducing problem:
gamma-launcher full-install --custom-gamma-definition 52004a05d95ea030447e034b71af0aae7542853d --anomaly Anomaly/ --gamma gamma_install/
gamma-launcher usvfs-workaround --anomaly Anomaly --gamma gamma_install --final Gamma

Log with faulty revision:
[xray_steamuser.log](https://github.com/Mord3rca/gamma-launcher/files/13821509/xray_steamuser.log)

Last working 1e80bf355b2920c0996e783669e1a4502aa6820a(GAMMA) revision:
[xray_steamuser_good.log](https://github.com/Mord3rca/gamma-launcher/files/13821751/xray_steamuser_good.log)

**Comment by Mord3rca** [comment]
To get your installation running, go to your final install (Anomaly folder if you don't use usvfs-workaround) folder and type:
```sh
cd bin/
rm Anomaly*.exe
for exe in AnomalyDX10AVX.exe AnomalyDX10.exe AnomalyDX11AVX.exe AnomalyDX11.exe AnomalyDX8AVX.exe AnomalyDX8.exe AnomalyDX9AVX.exe AnomalyDX9.exe; do wget "https://github.com/Grokitach/Stalker_GAMMA/raw/4549f3077d420ef9769fabec3d2219679047c5fd/G.A.M.M.A/modpack_patches/bin/${exe}"; done
```
This will DL November exes which aren't bugged.

Then, in GAMMA mod folder, do:
```sh
cp 'mods/165- Hunger Thirst Sleep UI htsb knifebinoc patches - xcvb/gamedata/configs/ui/ui_new_bars_16.xml' 'mods/164- Hunger Thirst Sleep UI 0.71 - xcvb/gamedata/configs/ui/ui_new_bars_16.xml'
```
In your case, since you are using usvfs:
```sh
cd <path/to/final>/gamedata/configs/ui/
rm ui_new_bars_16.xml
wget "https://github.com/Grokitach/Stalker_GAMMA/raw/main/G.A.M.M.A/modpack_addons/164-%20Hunger%20Thirst%20Sleep%20UI%200.71%20-%20xcvb/gamedata/configs/ui/ui_new_bars_16.xml"
```

Hope it helps

**Comment by sobkas** [comment]
It works, but only if I copy ui_new_bars_16.xml from mods/165- Hunger Thirst Sleep UI htsb knifebinoc patches - xcvb/gamedata/configs/ui/ui_new_bars_16.xml.

File downloaded from 164- Hunger Thirst Sleep UI 0.71 - xcvb doesn't work (it causes crashes when opening inventory)

**Comment by Mord3rca** [comment]
Closing, error in gamma definitions not in launcher
