### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by JoeyRheinhart** [Mord3rca/gamma-launcher#97]
https://github.com/Mord3rca/gamma-launcher/issues/64#issuecomment-1823565242

Have the same issue here with ERROR: Could not find a version that satisfies the requirement gamma-launcher (from versions: none).

On Linux Mint with latest pip, python, and git

**Comment by Mord3rca** [comment]
What command did you used ?
Did you followed this [comment](https://github.com/Mord3rca/gamma-launcher/issues/64#issuecomment-1823572137) ?

Quick note, if the folder is named **gamma-launcher**, please use: `pip install ./gamma-launcher` so pip know you want to install from a folder.

**Comment by JoeyRheinhart** [comment]
Its working now, sorry for the confusion!
